### ISSUE TITLE
See if we can get tablet apps list from some Play Store API

### ISSUE THREAD

**Issue by yohanboniface** [ideascube/ideascube#113]

**Comment by yohanboniface** [comment]
Other (maybe better because offline) option: https://github.com/androguard/androguard

In other words, have the "official" (i.e. part of the ideasbox project) apps locally, and read their metadata. As we also need apk to easily deploy apps on all the tablets, that may be strait forward in our process.

**Comment by barbayellow** [comment]
We definitely must have a deeper look at this kind of project since Google won't release in a near future any tablets fleet management solution.
