### ISSUE TITLE
arabic tags have no slug

### ISSUE THREAD

**Issue by yohanboniface** [ideascube/ideascube#118]
We need a more powerfull slug algo that can do ascii folding on all utf-8 (unidecode may be a good candidate).

**Comment by yohanboniface** [comment]
cf https://github.com/alex/django-taggit/pull/273#issuecomment-66955534

**Comment by yohanboniface** [comment]
cf https://github.com/alex/django-taggit/issues/179

**Comment by goingeast** [comment]
I have issue that first Chinese tag has no slug, then second Chinese tag's slug is "_1".

**Comment by yohanboniface** [comment]
Are you using ideascube, or are you just using django-taggit?

**Comment by bochecha** [comment]
```
$ pew new -p python3 test-slugs
...
Launching subshell in virtual environment. Type 'exit' or 'Ctrl+D' to return.
test-slugs$ pip install django
...
Successfully installed django-1.9.7
test-slugs$ python
Python 3.4.3 (default, Mar 31 2016, 20:42:37) 
[GCC 5.3.1 20151207 (Red Hat 5.3.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from django.template.defaultfilters import slugify
>>> slugify('林')
''
>>> 
test-slugs$ pip install python-slugify
...
Successfully installed Unidecode-0.4.19 python-slugify-1.2.0
test-slugs$ python
Python 3.4.3 (default, Mar 31 2016, 20:42:37) 
[GCC 5.3.1 20151207 (Red Hat 5.3.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from slugify import slugify
>>> slugify('林')
'lin'
```

https://pypi.python.org/pypi/python-slugify

I've used this on other projects, and it bugs me to no end that Django provides such a poor `slugify` implementation instead of just taking in python-slugify. :smile:

**Comment by bochecha** [comment]
Ah, and now I read the comments you mentioned above and see this module has already been mentioned. So much for arriving late to the party. :)
