### ISSUE TITLE
More granular permissions

### ISSUE THREAD

**Issue by yohanboniface** [ideascube/ideascube#125]
Something like:
- blog management
- server management
- user management
- entries management

we then also need a page to manage permissions per user.

**Comment by fheslouin** [comment]
+1 
We will need to have an : 
  - administrator account with all rights
  - several team leader account for blog posting / library posting

**Comment by yohanboniface** [comment]
Same need here in Bardarash. Not blocker at all, but at least having one more flag for server backup, stop/restart , wifi, etc. would help.

**Comment by barbayellow** [comment]
We do have this need for a future project in the media field (yeah !). We need several level of users, some able to upload content in the mediacenter but without the ability to read it (using the mediacenter as a kind of letterbox), and some able to read and upload content. I assume this is not a conventional need, and the project is not even a reality, but having a kind of granularity in user management could be a start to build upon.

**Comment by yohanboniface** [comment]
> some able to upload content in the mediacenter but without the ability to read it

Can you go onto more details? Seems awkward.
