### ISSUE TITLE
CSS bugged under Safari

### ISSUE THREAD

**Issue by yohanboniface** [ideascube/ideascube#148]
![capture d ecran 2015-07-10 a 21 35 52](https://cloud.githubusercontent.com/assets/146023/8627463/83e43ce8-274b-11e5-8bf2-09e6f3c8ff58.png)

I'm afraid it's because of using flex boxes. Problem is that in Australia, we'll have iPads.

**Comment by yohanboniface** [comment]
There is a Chrome for iPad: https://itunes.apple.com/en/app/chrome-web-browser-by-google/id535886823?mt=8

**Comment by lilinx** [comment]
CSS bugged under chrome in Ipads. I'll try to upload a screenshot

**Comment by lilinx** [comment]
Horizontal
![p1030973](https://cloud.githubusercontent.com/assets/5887117/8899889/3efe58d8-343a-11e5-980f-13a60ab5ac88.JPG)

Vertical
![p1030974](https://cloud.githubusercontent.com/assets/5887117/8899891/46b2f05c-343a-11e5-9ea9-296b80d20824.JPG)

Similar problem on my android phone

**Comment by yohanboniface** [comment]
May be flexbox related again. @providenz any chance you have a quick look on this specific case (the library home page on Chrome for iPad, I'm not talking about Safari itself)?

**Comment by lilinx** [comment]
This seems to display fine when you have rows of max. 3 items.
Any chance you can limit the number of items in a row?
It would be nice to have that fixed before I leave ; it will be difficult to update Mapoon after that.
