### ISSUE TITLE
Show basic system info

### ISSUE THREAD

**Issue by fheslouin** [ideascube/ideascube#158]
The server can run a basic bash script via cron every X min. The data gathered are recorded in a CSV file which look like this 

```
CURRENT_DATE;LAST_BOOT_DATE;LAST_BOOT_TIME;UPTIME_DAYS;UPTIME_HOURS;UPTIME_MINUTES;LOAD_1;LOAD_2;LOAD_3;CPU_USAGE;MEM_USED;SWAP_USED;BAT_STATUS;BAT_PRESENT;BAT_HEALTH;BAT_VOLTAGE_NOW;BAT_CURRENT_NOW;BAT_CAPACITY
```
We could build a basic system info page that will fetch the data from the CSV file. 

Let's see how fare we can go and if possible we could have a graphic display of the battery discharge, swap used, load, etc.

**Comment by fheslouin** [comment]
I don't think we need to use this bash script. Python should be able to fetch directly those infos. An other issue is open with all the details #255

**Comment by yohanboniface** [comment]
Shouldn't this issue be closed then? :)

**Comment by fheslouin** [comment]
Of course ! I forgot
