### ISSUE TITLE
server log export

### ISSUE THREAD

**Issue by yohanboniface** [ideascube/ideascube#16]
We want to have a "log exporter" that do a bunch of export into a zip that is then downloaded, including:
- dmesg
- syslog
- interfaces file content
- ping 8.8.8.8 result
- ping ideasbox.lan result
- check version of the various softwares (OS, ideasbox.lan…)
- …

**Comment by fheslouin** [comment]
This is done via Ansible 
  - Nginx log 
  - kern.log
  - messages
  - syslog 
  - System info including 
    - lscpu
    - lshw
    - hwinfo
    - lspci
    - lsusb
    - lsblk
    - df
    - ip a l 
    - ps aufx
    - systemctl status

Should I had something else ?

**Comment by yohanboniface** [comment]
@fheslouin ideally, yes, we should also grab the ideascube application logs. But I think this needs a bit more setup, cf #24.

**Comment by letompouce** [comment]
> a bunch of export into a zip that is then downloaded

Keep in mind: binary zip file vs plain text rsync, all of this over shitty connections.
