### ISSUE TITLE
Add the possibility to change domain name in Nginx config

### ISSUE THREAD

**Issue by fheslouin** [ideascube/ideascube#160]
Would it be possible to add in base.conf a variable too change the domain name ? 
From ideasbox.lan to an_other_name.lan

**Comment by yohanboniface** [comment]
That should already be the case, have you tested pointing on the webserver with the domain of your choice?

**Comment by yohanboniface** [comment]
Ah, you may need to override ALLOWED_HOSTS in your local config.

**Comment by yohanboniface** [comment]
The only thing that can't be configured at the moment is Nginx itself, but you added koombook there already so I move out this issue from current milestone.
