### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by mariefontanel** [ideascube/ideascube#169]
Two translations issues :
-  "restart" => "redémarrer"
- "last post" => "dernier post" (it used to be in plural in the ideasbox server but it changes for the Koombook)

**Comment by yohanboniface** [comment]
https://www.transifex.com/ideasbox/public/ :)

**Comment by rodo** [comment]
@yohanboniface the link is wrong, think this one is right https://www.transifex.com/ideascube/ideascube/

**Comment by yohanboniface** [comment]
Correct! :)
We renamed the project some weeks ago, and I've not tracked every link around the issues ;)

**Comment by rodo** [comment]
@mariefontanel I've just checked, seems to be fixed in Transifex

**Comment by yohanboniface** [comment]
Thanks for the check, @rodo, closing so :)
