### ISSUE TITLE
State on wiki usage, or move it to documentation

### ISSUE THREAD

**Issue by benoitbryon** [ideascube/ideascube#176]
Following https://github.com/ideas-box/ideasbox.lan/pull/174#discussion_r42367140, wiki should be deprecated and its content moved to docs/, or fixed to be up to date and usable by community.

**Comment by bochecha** [comment]
Ideascube moved to Framagit.

This issue has been migrated.

Please continue the conversation there:

https://framagit.org/ideascube/ideascube/issues/176
