### ISSUE TITLE
Nice default icons on media center

### ISSUE THREAD

**Issue by yohanboniface** [ideascube/ideascube#180]
To be done by a designer :)

**Comment by barbayellow** [comment]
A designer has been working ! (thx Manuella). Here are the icons : 
![blog](https://cloud.githubusercontent.com/assets/4816690/11040384/41addfc0-870c-11e5-8024-c8cb359020f2.png)
![image](https://cloud.githubusercontent.com/assets/4816690/11040382/41aba5fc-870c-11e5-9a02-4687e0711a6e.png)
![library](https://cloud.githubusercontent.com/assets/4816690/11040386/41acc02c-870c-11e5-9c6a-765671567b05.png)
![media-center](https://cloud.githubusercontent.com/assets/4816690/11040383/41ac87ec-870c-11e5-8b65-f62583bb1d41.png)
![pdf](https://cloud.githubusercontent.com/assets/4816690/11040387/41b198ae-870c-11e5-9bd7-5bee0f1c232c.png)
![sound](https://cloud.githubusercontent.com/assets/4816690/11040385/41aff4f4-870c-11e5-9207-2850bbd827e5.png)
![texte](https://cloud.githubusercontent.com/assets/4816690/11040389/41c0de90-870c-11e5-8d15-bbaf3623b5fc.png)
![video](https://cloud.githubusercontent.com/assets/4816690/11040388/41bd84ca-870c-11e5-8025-8fe1433485d7.png)
