### ISSUE TITLE
Add typed media center page

### ISSUE THREAD

**Issue by yohanboniface** [ideascube/ideascube#183]
And link in the media center home.

**Comment by yohanboniface** [comment]
Made a first version, but the kind parameter is not passed to the tag cloud. So this is yet to be done for closing the issue.
Plus unittests.

**Comment by mgautierfr** [comment]
Is this still a open issue ?
We can filter media per kind in the mediacenter home page and we can also link to a filtered page with the right querystring in the url.

Is there something more to do ?
