### ISSUE TITLE
STORAGE_ROOT is hardcoded in Nginx config

### ISSUE THREAD

**Issue by yohanboniface** [ideascube/ideascube#194]
We have /var/ideascube/ is harcoded, so when one changes STORAGE_ROOT Nginx fails to find medias and statics.

**Comment by fheslouin** [comment]
This is not a problem anymore as the KoomBook is now using the same dir as the IdeasBox. The STORAGE_ROOT is still hardcoded in Nginx but we can leave it has it is.
