### ISSUE TITLE
Delete a blog post

### ISSUE THREAD

**Issue by fheslouin** [ideascube/ideascube#199]
There is no possibility to delete a blog spot. 
Would it be possible to add a link below "edit" to also delete an unwanted blog post ?

**Comment by yohanboniface** [comment]
Humm, yeah, that's missing. In the meantime you can just change its status so non admin people will not see it.

**Comment by fheslouin** [comment]
In status, I can switch the post to "deleted", but it's not really obvious at first look

**Comment by yohanboniface** [comment]
Do we still need hard delete?
