### ISSUE TITLE
link blog post and media

### ISSUE THREAD

**Issue by fheslouin** [ideascube/ideascube#201]
It could be interesting to be able to create a blog post and to link media from the media center. 

Currently, it can be done by creating a link using the following URL address  : http://koombook.lan/fr/mediacenter/tag/write_my_tag

With write_my_tag a known tag from the media-center

Maybe we could find a nice way to link more media from the blog post. 

This is a non urgent issue and we have to see how the blog section is used

**Comment by yohanboniface** [comment]
That's actually already doable: copy-paste the media URL in the media edit box, and you'll have the media in the blog post ;)
