### ISSUE TITLE
Kiwix : .zim autoload 

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#209]
In Kiwix, it could be great to bypass the page "load" screen and access directly to the content. 
This is what I mean by the "load page"  : 
![welcome to kiwix server - mozilla firefox_020](https://cloud.githubusercontent.com/assets/4816690/11123130/906522e6-895e-11e5-917c-4fb63b5dafab.png)

**Comment by kelson42** [comment]
Making a direct deep link to the content welcome page (in vhost or html) should fix the problem... That said making a vhost for each content delivered by Kiwix might be a little bit overkill.

**Comment by barbayellow** [comment]
This will be included with the package manager.

**Comment by mgautierfr** [comment]
This seems to be fixed now.
