### ISSUE TITLE
Register users phone number

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#215]
Message from a box manager on the field that could be integrated as a feature : 

"Not sure if this is possible or who to speak to about it, but I was just wondering if there was some way to add peoples phone numbers when they register with the Ideasbox? It would come in handy for when they loan out books, I could send them a text message the day before to remind them that the books are due back."

**Comment by yohanboniface** [comment]
Also needed for Burundi migration. I'll add the field.
Question: in the burundi boxes, we have two fields (tel1, tel2), I'd suggest keeping only one, but allowing multiple values. Thoughts?

**Comment by yohanboniface** [comment]
added one field with burundi work
