### ISSUE TITLE
Dbus not working on Mac. How would you like to deactivate it in that case?

### ISSUE THREAD

**Issue by endeav** [ideascube/ideascube#218]
I had to comment like that.

```
diff --git a/ideascube/serveradmin/wifi.py b/ideascube/serveradmin/wifi.py
index 62d8bb1..56c2b6d 100644
--- a/ideascube/serveradmin/wifi.py
+++ b/ideascube/serveradmin/wifi.py
@@ -3,7 +3,7 @@ from itertools import groupby
 from operator import attrgetter
 from uuid import uuid4
 
-from dbus import DBusException
+# from dbus import DBusException
 
 from django.utils.translation import ugettext as _
 
@@ -99,20 +99,20 @@ class AvailableWifiNetwork(object):
                     'psk': wifi_key,
                     }})
 
-        try:
-            return KnownWifiConnection(NMSettings.AddConnection(settings))
-
-        except DBusException as e:
-            excname = e.get_dbus_name()
-            name = 'org.freedesktop.NetworkManager.Settings.InvalidProperty'
-
-            excmsg = e.get_dbus_message()
-            keyprop = '802-11-wireless-security.psk:'
-
-            if excname == name and excmsg.startswith(keyprop):
-                raise WifiError(_('Invalid Wi-Fi key'))
-
-            raise
+        #try:
+        return KnownWifiConnection(NMSettings.AddConnection(settings))
+
+        # except DBusException as e:
+        #     excname = e.get_dbus_name()
+        #     name = 'org.freedesktop.NetworkManager.Settings.InvalidProperty'
+        #
+        #     excmsg = e.get_dbus_message()
+        #     keyprop = '802-11-wireless-security.psk:'
+        #
+        #     if excname == name and excmsg.startswith(keyprop):
+        #         raise WifiError(_('Invalid Wi-Fi key'))
+        #
+        #     raise
 
     def connect(self, wifi_key=None):
         if self._connection is not None:
```

**Comment by endeav** [comment]
```
 File "~/ideascube/ideascube/serveradmin/urls.py", line 3, in <module>
    from . import views
  File "~/ideascube/ideascube/serveradmin/views.py", line 14, in <module>
    from .wifi import (
  File "~/ideascube/ideascube/serveradmin/wifi.py", line 6, in <module>
    from dbus import DBusException
  File "~/ideascube/env/lib/python2.7/site-packages/dbus/__init__.py", line 82, in <module>
    import dbus.types as types
  File "~/ideascube/env/lib/python2.7/site-packages/dbus/types.py", line 6, in <module>
    from _dbus_bindings import (
ImportError: No module named _dbus_bindings
```

**Comment by bochecha** [comment]
We use DBus to talk to NetworkManager. As far as I know, NetworkManager does not exist on Mac OSX.

So I guess the "solution" here is to just not make the Wi-Fi management interface available on Mac OSX.

The code already takes care of NetworkManager not being available. It seems I failed to do the same for DBus, though.

I doubt you needed to comment all these lines, though. Can you try uncommenting them all, except for this one:

```
# from dbus import DBusException
```

(I mean, keep only that line commented, uncomment all the other ones)

That should be enough to not get a crash any more, and instead just get the "Wi-Fi is disabled" message.

If you can confirm, then the fix is trivial: we just need to move the DBus import line in the `try` block just a few lines below.

**Comment by Natim** [comment]
Actually if we do not import ``DBusException`` we won't be able to use it in the Except clause.

I agree that we should probably add an error message on the interface saying that Wifi configuration is not available or even deactivating the card in that case.

**Comment by bochecha** [comment]
> Actually if we do not import DBusException we won't be able to use it in the Except clause.

You'll never reach that `except` clause though, when using the app normally, because you'll get a `WifiError` in `enable_wifi()`.

> I agree that we should probably add an error message on the interface saying that Wifi configuration is not available

Putting the `DBusException` import in the `try` block should be enough to do just that.

Which is why I asked @endeav to try it and confirm. :wink:

**Comment by endeav** [comment]
Apparently I don't get the error anymore, not even if I uncomment those lines of code that I mentioned in my first comment. Not sure what happened, but it works.

**Comment by endeav** [comment]
@bochecha if I move `from dbus import DBusException` in `try` block it works, indeed. Thank you!
