### ISSUE TITLE
Permanent menu on the top of the page

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#222]
When users go on wikipedia or kalite or any app which not included in the ideascube app, they can't go back on the homepage unless they enter the url in the address bar. It would be nice to have always a top bar allowing users to go back on the home page, whether they are in wikipdia, kiwix, kalite or whatever.

**Comment by fheslouin** [comment]
Experimented today in RDC. People sometime can't find there way back to ideascube.
I can easily inject html code with with Nginx to show this menu. It could deployed with Ansible

**Comment by barbayellow** [comment]
This is technically feasible. However, this implies some UI changes. 

- Should we minimize the logo ?
- Should we leave the "connection" link always in the header, knowing we can't handle anything dynamically with the Nginx trick (only static html), so we would link directly to a connexion page, but then, once connected where would you be redirected ?
- Should we remove this link, which could seem strange for the user

This all I can see as far as I try to figure out how to do perform this change. But I'm sure there is more.
