### ISSUE TITLE
Allow the Wifi manager for Manual configuration

### ISSUE THREAD

**Issue by Natim** [ideascube/ideascube#232]
- [ ] Some Wifi doesn't publish their SSID. We need a way to connect to them using a manual configuration and by entering the SSID.
- [ ] Could be nice to be able to read the configuration from the History.

**Comment by bochecha** [comment]
Ideascube moved to Framagit.

This issue has been migrated.

Please continue the conversation there:

https://framagit.org/ideascube/ideascube/issues/232
