### ISSUE TITLE
Hide hotspot koombook / ideasbox from the hostpot listed in the wifi module

### ISSUE THREAD

**Issue by fheslouin** [ideascube/ideascube#233]
I think it could be confusing for people to see the hotspot created by the device. Worst they could try to connect to it. This will not cause any damage but they could get lost somehow.

**Comment by bochecha** [comment]
How can we know which network to hide?

Does it have a fixed name?

**Comment by fheslouin** [comment]
Yes, so far, the network has always been koombook or ideasbox. But if people outside of BSF want to use ideascube, if the do not call theire network koombook or ideasbox the will see it in the list. 
It is just something people have to know.

Maybe I'm missing one or two use case where it could be useful to connect to an other ideasbox or koombook hotspot, but the problem then is that all the koombook / ideasbox has always the same hotspot name. 

I guess the best way of achieving that is to read the file /etc/hostapd/hostapd.conf where the "ssid=" is stored.
