### ISSUE TITLE
Add a button to see password when login in

### ISSUE THREAD

**Issue by yohanboniface** [ideascube/ideascube#236]
Very often the box is deployed with mixed azerty/qwerty/whateverty with many keyboard layout around, so people may doesn't understand what they are typing exactly.

I'm thinking about a button next to the password field that changes the field type to "text" during 3 seconds or something like that (that's the idea that comes out during the training of today here in Melkadida).

Any better idea around? :)

**Comment by bochecha** [comment]
Could do something like mobile OSes do: each typed key is visible for a couple of seconds only.

Not sure how that would be done, but the good point about that is it could be done by default, and you wouldn't need any additional button at all.

**Comment by yohanboniface** [comment]
On a UI/UX level, that would be really nice. But on the technical level, I'm not sure how to achieve that in a simple and elegant way.

**Comment by bochecha** [comment]
Yeah, we'd have to replace the last typed character in the input (either on a timeout, or when a new character is typed, in which case we need to cancel previous timeouts), which means saving the actual password somewhere else (a hidden input?)

If only browsers would just do that for us. :stuck_out_tongue_winking_eye:

**Comment by yohanboniface** [comment]
One counter argument though: a lot of box beneficiaries are not very comfortable on a computer, and may not see the typed letter in time because they have looking at the keyboard while typing.

**Comment by yohanboniface** [comment]
http://www.sitepoint.com/examples/password/MaskedPassword/demo.html (from http://www.sitepoint.com/better-passwords-1-the-masked-password-field/ )

**Comment by yohanboniface** [comment]
I've pushed a first naive version, because I wanted to take advantage of being still here to test it during my training of today.
@bochecha can you make a quick "post commit review" (a new concept :p )? :)

**Comment by bochecha** [comment]
Just a [minor doubt](https://github.com/ideascube/ideascube/commit/13c88b995e3352f8e14e9cba8ac272cbe0fb41e9#commitcomment-14920689), but I'm not sure it could end up causing problems or not.

Otherwise looks good.

Note that I've only looked at the code, I haven't tried it out. :smile:

**Comment by yohanboniface** [comment]
Looks like this :)

![show-password](https://cloud.githubusercontent.com/assets/146023/11751457/a313d0ba-a04a-11e5-8c58-e103153f9568.gif)
