### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by yohanboniface** [ideascube/ideascube#24]
We need logs, because we want to have as much info as possible when a bug will be reported.

But we should keep in mind to rotate the logs not to explode the FS after a long time of logging.

**Comment by fheslouin** [comment]
Most log file are rotated with Ansible, except uwsgi log file, I open an issue in Ansiblecube https://github.com/ideascube/ansiblecube/issues/14

Can we close this issue ?

**Comment by yohanboniface** [comment]
> Can we close this issue ?

Humm, this ticket is more about generating logs (i.e. logging what's going on in ideascube application), so I'd keep it open (but the ansiblecube one is great :) ).

**Comment by letompouce** [comment]
> Most log file are rotated with Ansible

Actually ansible installs `logrotate(1)` but doesn't configure it further, which is the issue - and the solution as well. This is all described in https://github.com/ideascube/ansiblecube/issues/37
