### ISSUE TITLE
Captive portal

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#247]
When a user access to ideascube and when the server is connected to the Internet, it acts as a transparent proxy. We want the user to go through the home page of the ideas cube. Hence the captive portal.

**Comment by yohanboniface** [comment]
http://andybev.com/index.php/Setting_up_a_captive_portal_from_scratch_using_Debian

**Comment by barbayellow** [comment]
ping @letompouce | @fheslouin. Would it be possible to set up this with ansiblecube ?
