### ISSUE TITLE
Library app forms enhancements

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#248]
Admins should have the ability to edit the forms :
- add new field
- remove useless ones

**Comment by yohanboniface** [comment]
Is that a real need? Do you have concrete use stories about that?
Ideascube will never compete with PMB or such, so when librarians want a full featured library management tool, we may ship with a third party package instead, imho.

**Comment by barbayellow** [comment]
You might be right. I'll get back with more feedback on this one.
