### ISSUE TITLE
Blog post on the portal homepage

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#251]
We should offer the ability for the ideascube admin to publish a blog post directly on the home page. Exactly as a regular "card" with a title, a short description and an image. Link : the blog post. It could be a specific blog post, or a semi automatic process : latest post or a random post.

**Comment by yohanboniface** [comment]
Do you remember that you made me remove that from the homepage? :p

But I agree that's nice to have. I'd go for a semi automatic process for now: if there is a blog post from, say, less than a week old, display it. But I'm not sure the blog is even used anywhere at this time (maybe Burundi, but that needs to be confirmed).

**Comment by barbayellow** [comment]
Yes I do ! But that would be a different layout. The blog post would fit in a "card". Just a s it was a feature such as wikipedia or Gutenberg. We'll check if this feature is used in Burundi next week (call delayed). I agree, this is not a priority.

**Comment by barbayellow** [comment]
I get more information with the project manager (yes, it does not come from the field :), and I'll write more about it.
