### ISSUE TITLE
Show IP and mac address 

### ISSUE THREAD

**Issue by fheslouin** [ideascube/ideascube#255]
In RDC the network administrator have to manage a little bit the KoomBook and in some case they have to add the KoomBook into the local network. In order to achieve this, they have to know some network information about the KoomBook. 
- Eth0 IP address + MAC address
- Wlan1 IP address + MAC address

I think we could add this in the admin page left menu below the ideascube version for instance.

**Comment by yohanboniface** [comment]
WANT :)
