### ISSUE TITLE
Content and user administration

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#261]
When a user is deleted, all files and blogposts generated by the user are removed. We should be able to remove a user without removing any content.

**Comment by yohanboniface** [comment]
We have those options:

1. allow blogs to have no author (remove the db constraint, adapt the code not to rely on a non null author)
2. before deleting, replace author by some "default" author we would create on each box
3. do not allow to delete users that are authors, and add an option to deactivate them only (means author will not be allowed to login again)

My preference is option 3. But what would help decide is to know what we want to delete users for.

**Comment by yohanboniface** [comment]
After a quick discussion with @barbayellow: we prevent deleting any user that has a non nullable foreign key. So it's still possible to delete a user that has no non nullable FK (for example if someone creates twice the same user by mistake), and it's still possible if we really want to go by every blog post created by the user we want to delete and replace it by another author. Also it's possible to remove the "staff" status from a user if we want to prevent this user to login and do anything on the platform.

That's first iteration on the issue, that at least prevent the current scenario, which is very bad, of deleting content when deleting a user. And let's see if we have any specific feedback then.
