### ISSUE TITLE
User creation: setting password

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#274]
When creating a user from the web interface, there is something strange : we can't set the password on the main screen. I must first create the user, then save, then select in the left menu the option "set password". It's a little bit confusing. 

We should be able to set the password int the user creation screen AND the menu on the left should be "change password", once the user has been created.

**Comment by yohanboniface** [comment]
99% of the created users does not have password: only staff users have one. I don't think we should pollute the main form with staff only fields.
