### ISSUE TITLE
Augmenter le nombre de tags affichés sur la home du mediacenter?

### ISSUE THREAD

**Issue by williamlegeneral** [ideascube/ideascube#287]
Sur un koombook en RCA, lorsque je crée un nouveau média dans le mediacenter, celui-ci ne prend pas en compte les nouveaux tags que j'ajoute.

**Comment by yohanboniface** [comment]
Quelle est la version d'ideascube? Visible sur http://ideasbox.lan/en/server/power/ par exemple.

**Comment by barbayellow** [comment]
Compris : seuls les x tags les plus utilisés apparaissent sur la page d'accueil du média center. Peut-être faudra t-il augmenter ce chiffre (ou pas pour les terminaux mobiles). En tout cas ce n'est plus un bug !

**Comment by mgautierfr** [comment]
The #698 have been recently opened and it is exactly the same bug than here.
I'm closing this one as it is better to have only one issues per bug and there is bigger discussion there.
