### ISSUE TITLE
Backup permission problem

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#292]
THe backup feature does not work. When throug the KoomBook web interface, we try to use the backup function http://koombook.lan/fr/server/backup/, we get this error message : PermissionError at /fr/server/backup/

See attach for more information.
[kb-error.pdf](https://github.com/ideascube/ideascube/files/132228/kb-error.pdf)

**Comment by yohanboniface** [comment]
This needs to be addressed on the ansiblecube repository. It's an install issue.
