### ISSUE TITLE
After installing Ideascube, nginx fails to run

### ISSUE THREAD

**Issue by bochecha** [ideascube/ideascube#298]
The `nginx` package comes with a `default` configuration pre-installed, and pre-enabled:

```
/etc/nginx/sites-enabled/default
```

But then when we install the `ideascube` package, we add a new one:

```
/etc/nginx/sites-enabled/ideascube
```

The two conflict, and therefore nginx fails to run after we install Ideascube.

We need to either make the two not conflict, or disable the `default` config as part of the Ideascube installation process.

**Comment by yohanboniface** [comment]
> We need to either make the two not conflict

I'd say this option. What is the conflict?

**Comment by bochecha** [comment]
> What is the conflict?

Did I not say that in the description of the issue? But... that was one of the most important information to provide... :confused: 

So here are the logs:

```
Feb 25 11:56:19 old-dell nginx[5670]: nginx: [emerg] a duplicate default server for 0.0.0.0:80 in /etc/nginx/sites-enabled/ideascube:9
Feb 25 11:56:19 old-dell nginx[5670]: nginx: configuration file /etc/nginx/nginx.conf test failed
```

The problem is this line in the `/etc/nginx/sites-enabled/ideascube` file:

```
    listen      80 default_server;
```

This conflicts with this line in the `/etc/nginx/sites-available/default` file:

```
        listen 80 default_server;
```

If something connects to the box on port 80, but the requested host does not match any of the configured `server_name` values, then nginx routes the request to the configured `default_server`.

Obviously, there can be only one default server. :smile: 

So the first question is: do we want to be the default server?

If so, the only solution I can see is to disable the default nginx config.

---

In addition, I just found that the `default` config has this line, but the `ideascube` one does not:

```
        listen [::]:80 default_server;
```

**Comment by yohanboniface** [comment]
> So the first question is: do we want to be the default server?

I'd say no. Ansiblecube may want to override some tricks on the default, but I'd say that this is not ideascube stuff. In my opinion, ideascube should just register itself as site, with the given name and using the uswgi socket, etc.

**Comment by bochecha** [comment]
I'd tend to agree, especially since Django will refuse to work if the app is called with a name that isn't configured.

And if we'd land on ideascube simply because it was the default host and the request didn't match anything else, then we'd be in that case.

**Comment by fheslouin** [comment]
In ansiblecube I'm always removing the default nginx conf. As you said there is a conflict with the default server conf. 
Beside that, I have an other conflict with the 443 port as I'm using SSLH software to redirect 22 port to 443 port. I think that using the 443 port in Ideascube is more or less useless because we don't have a signed certificate. We could have a self signed cert that will end up on a warning screen from any web browser...

**Comment by barbayellow** [comment]
I do understand that changing the default ngnix configuration should not be done by ideascube. However we should think about having something working "out of the box" once ideascube is installed with apt. Maybe we should make ideascube running on a specific port for the default installation ? :8080 ?

**Comment by bochecha** [comment]
We just discussed this offline with @barbayellow , @fheslouin  et @letompouce .

The consensus was that we should just remove the `default_server` from the ideascube config, because clients only access the ideascube app through names like `koombook.lan` which are explictly defined in the nginx config for ideascube.
