### ISSUE TITLE
Add a default "ideascube" logo

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#302]
So far we only have a "ideasbox" logo out of the box (meaning with the default conf file) which is a BSF' project. We'd like this project to be used not only by BSF. We need a "neutral" logo by default.

**Comment by yohanboniface** [comment]
A favicon will also be needed, see #466

**Comment by barbayellow** [comment]
It's here ! It's alive !!!

Logo + favicon

![favicon-ideasbox](https://cloud.githubusercontent.com/assets/4816690/20005751/3b90e0d4-a294-11e6-9507-66376506c0f1.png)
![favicon-ideascube](https://cloud.githubusercontent.com/assets/4816690/20005754/3b91c8be-a294-11e6-9de6-165157402ae4.png)
![favicon-koombook](https://cloud.githubusercontent.com/assets/4816690/20005755/3b920608-a294-11e6-8745-d936eabd1a04.png)
![ideascube-logo](https://cloud.githubusercontent.com/assets/4816690/20005753/3b911e82-a294-11e6-9126-80bf04689a51.png)
