### ISSUE TITLE
Software category in the Mediacenter

### ISSUE THREAD

**Issue by fheslouin** [ideascube/ideascube#309]
We have currently a simple role in Ansiblecube to present in a webpage a listing of folder containing free as beer and free as a speach software. This is not really optimized as we have only a long list of software without any description. Furthermore the software are not up to date, which is kind of a problem. 

My thought was to use the media center and the mass import script to add those software directly in the mediacenter. A tag like "Software" could be used to show only the software. The end user would have the ability to sort, search and read some description before downloading the software. 

I think It would be easy to implement in the mediacenter ? 

Any thought ?

**Comment by barbayellow** [comment]
+1. The catalog feature could help us t achieve this goal cc @yohanboniface

**Comment by fheslouin** [comment]
Could it be possible to have this feature in the next release ?
