### ISSUE TITLE
Le label du bouton de téléchargement dans le media center ne correspond pas à l'action effectuée

### ISSUE THREAD

**Issue by williamlegeneral** [ideascube/ideascube#315]
Bonjour, 

Je vous ai envoyé un mail hier soir. J'ai fait une erreur de mot. Le problème posé ne se situe par sur le cybook plutôt sur le KOOMBOOK.
A titre de rappel. Le service Media Center concernant le téléchargement des vidéos 
1- Au lieu d'avoir comme name sur le bouton "télécharger une vidéos" la commande conserve encore le name "Télécharger des documents".
2- Lorsqu'on clique sur le bouton au de faire afficher une boîte de dialogue "Enregistrer" le commande lance au contraire la videos.
Ainsi, pour télécharger il faut toujours effectuer un clic droit et choisir la commande enregistrer dans le menu contextuel. 

Bonne Journée.

**Comment by mgautierfr** [comment]
This is related to #399.
#399 fixes the first point (only) of this bug.

**Comment by mgautierfr** [comment]
For the second point (download instead of playing the video), we need to change the "Content-type" http header of the answer to : "octet/stream".
This way the browser will no try to read the content anymore so fallback on download.

**Comment by yohanboniface** [comment]
For PDF, I think we are happy with it being opened in the browser by default (while audio and videos already have their player in the page, images are displayed…).
So we may keep this button as "open document", and optionally add a "download document" that actually download it.

**Comment by fheslouin** [comment]
By the way, could we add font awesome icons to quickly identify the action, that will help people.

**Comment by bochecha** [comment]
Ideascube moved to Framagit.

This issue has been migrated.

Please continue the conversation there:

https://framagit.org/ideascube/ideascube/issues/315
