### ISSUE TITLE
Quick Install process

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#324]
I tried to run ideascube on a virtual machine using VirtualBox. I did the recommended installation using ideascube repository http://ideascube.readthedocs.org/en/latest/install/ on a debian 8  and always got the same ngnix error : http://pastebin.com/9C67vxTs

It's not a "real" issue, our goal is not to run ideascube on a vm. However we should find a way to install ideascube quite easily either with a vm or within a docker image (see https://github.com/ideascube/ideascube/pull/205) to be able to run this software without being a sys admin - which is an **ABSOLUTE** necessity if we want to grow the adoption rate of this software, within BSF and outside BSF.

**Comment by barbayellow** [comment]
a raspberry pie image should be interesting aswell. Yes I also tried http://ideascube.readthedocs.org/en/latest/install/  on a raspberry pie with no big hopes and no results except this traceback : 

`pi@raspberrypi:~ $ sudo apt-add-repository 'deb http://repos.ideascube.org/debian/ jessie/'
Traceback (most recent call last):
  File "/usr/bin/apt-add-repository", line 167, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 105, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 595, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 89, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/jessie
`

**Comment by barbayellow** [comment]
because I'm dying to be able to show the catalog feature tio the content team.

**Comment by bochecha** [comment]
> I tried to run ideascube on a virtual machine using VirtualBox. I did the recommended installation using ideascube repository http://ideascube.readthedocs.org/en/latest/install/ on a debian 8 and always got the same ngnix error : http://pastebin.com/9C67vxTs

This is #298

**Comment by barbayellow** [comment]
thx @bochecha I'm closing this one and continue to comment on #298
