### ISSUE TITLE
Only categories with file should appear

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#333]
In the media center, empty categories should be hidden. Example : if there are no pdf files, then the pdf cat should not appear in the right col.

**Comment by yohanboniface** [comment]
cc @mgautierfr this is to be taken into account on the "search based navigation" refactor :)

**Comment by yohanboniface** [comment]
This means live requesting which values are available for the current search. That could work for kind or lang, but that will be a bit harder to achieve this for tags, given that it's a multi value, and SQLite doesn't know about multivalues column.

**Comment by mgautierfr** [comment]
This is partly fix by PR #335.
Only kind and lang are hidden when empty.

For tags we may assume that if a tag is present in the db, it is pointing to at least a content (?)
We could filter tags to show only tags pointing to the displayed documents (if they are already filtered) but as @yohanboniface said, it a bit more complex. This is possible but I think we could delay it.

**Comment by yohanboniface** [comment]
Fixed with #335
