### ISSUE TITLE
Broken cards link for kiwix library 

### ISSUE THREAD

**Issue by fheslouin** [ideascube/ideascube#338]
1. Wikipedia Kirundi (wikipedia.ki) is installed and wikipedia.rn is called instead
2. Gutenberg Fr is installed and gutenberg.mul is called instead
3. tedxgeneva2014.fr is installed and tedxgeneva-2014.fr is called, same issue for all Ted ZIM. There is no "-" between the name and the year.

**Comment by yohanboniface** [comment]
>  Wikipedia Kirundi (wikipedia.ki) is installed and wikipedia.rn is called instead

ki is wrong lang code for [kirundi](https://fr.wikipedia.org/wiki/Liste_des_codes_ISO_639-1), so we need to handle that when generating the kiwix.yml file. cc @letompouce 
 
> Gutenberg Fr is installed and gutenberg.mul is called instead

Fixed :)

> tedxgeneva2014.fr is installed and tedxgeneva-2014.fr is called, same issue for all Ted ZIM. There is no "-" between the name and the year.

Fixed :)

**Comment by letompouce** [comment]
> s/.ki/.rn/

Fixed :)
