### ISSUE TITLE
Sign Languages in the media center

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#343]
There is no way at the moment to qualify a media as a media in sign languages. There is an iso specification for sign languages. It's  on 3 characters. At the moment, the command ideascube import_medias something.csv does not tolerate more than 2 characters for the language.

**Comment by yohanboniface** [comment]
It's missing in Django [LANG_INFO](https://github.com/django/django/blob/490107f14dbf9445e145aea1157b27e7ef407214/django/conf/locale/__init__.py) so we should add it in our `EXTRA_LANG_INFO`.
According to [this page](https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes) the code is `sgn`.
It seems there also more specific ones (like [ase](https://en.wiktionary.org/wiki/American_Sign_Language)), but we may start with a more generic one and move forward with more info, more precise needs later.
