### ISSUE TITLE
Links on card 

### ISSUE THREAD

**Issue by fheslouin** [ideascube/ideascube#345]
Some time the user does not know where to find the link on the card. It can be on the "App" name or in the language name as in the new card. So it can be a little bit confusing sometime. 
- First improvement would be to add a link on the image 
- Second improvement would be to enable a link on the whole card and we don't care about where the user is clicking...

**Comment by barbayellow** [comment]
This willt be a problem for the cards with multiple entries. Ex : wikipedia with multiple language entries. 
2 solutions : 
* the whole card is clickable but we will have to we give up the multiple entries cards 
* we keep the multipla entries cards but only the text is clickable. Which in term of UX is imho less efficient.

**Comment by bochecha** [comment]
Pretty sure this is now done:

* with the move to cards as packages we don't have multiple links (e.g languages) on a single card any more
* with the move to the PureCSS grid the whole card is now clickable.

Closing, please reopen if I misunderstood something.
