### ISSUE TITLE
On small screen "tags" and "types" goes to the bottom page

### ISSUE THREAD

**Issue by fheslouin** [ideascube/ideascube#346]
When we are using the media-center on small screen (typically on Danew tablet) the CSS grid box put the "tags" and "types" boxes at the bottom of the page. 
This is not convenient because the user has to scroll all the way down to select media type or tags. 

These boxes should be put at the top of the webpage.

**Comment by mgautierfr** [comment]
The "tags", "types", "lang" boxes are at top the page on small screen.

Few months ago, I rewrite the to use pure css grid system. I've probably fix this bug at the same time.
@fheslouin, @barbayellow, can you confirm that this bug should be closed or if there is still something to do ?

**Comment by barbayellow** [comment]
it's fine now. The bug can be closed. 
![image](https://cloud.githubusercontent.com/assets/4816690/22545601/abbed05a-e939-11e6-8864-09a5e4d88c8d.png)
