### ISSUE TITLE
New language in media center

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#356]
For a specific project, we need a new language in the media center : sorani kurdish. The iso code is on 3 letters :  ckb http://www-01.sil.org/iso639-3/documentation.asp?id=ckb

Is it possible to add it in the mediacenter ? 
Is it possible btw to use three letters to identify a language?

**Comment by bochecha** [comment]
> Is it possible btw to use three letters to identify a language? 

There is no reason why it wouldn't be possible. At least once #427 is merged.

In fact, #427 already adds codes like `zh-hant`, so a 3-letters code should be no problem. :)

**Comment by bochecha** [comment]
So, looking at [the Wikipedia page for this language](https://en.wikipedia.org/wiki/Central_Kurdish), it seems that this languages is:

* not bidirectional
* the name is 'Soranî'
* the local name is 'سۆرانی'

Can anybody confirm that this is right?

**Comment by yohanboniface** [comment]
> not bidirectional

Seems bidi to me
