### ISSUE TITLE
ideascube should not issue a fatal error when a remote already exists

### ISSUE THREAD

**Issue by letompouce** [ideascube/ideascube#357]
### Actual result

    # ideascube catalog remotes add "Kiwix" "Kiwix ZIM content" http://catalog.ideascube.org/kiwix.yml
    IDEASCUBE_ID=idb_jor_alhashmi
    Importing settings from ideascube.conf.idb_jor_alhashmi
    
    CommandError: There already is a "Kiwix" remote
    # echo $?
    1

This should not raise a fatal error. If the remote already exists, fine, let's move forward then!

### Expected result

    # ideascube catalog remotes add "Kiwix" "Kiwix ZIM content" http://catalog.ideascube.org/kiwix.yml
    IDEASCUBE_ID=idb_jor_alhashmi
    Importing settings from ideascube.conf.idb_jor_alhashmi
    
    CommandWarning: "Kiwix" remote: been there, done that. Let's move forward.
    # echo $?
    0

**Comment by bochecha** [comment]
I'm guessing the exit status is important for you because you run those commands in ansible, and having an error here makes your playbooks fail?

**Comment by letompouce** [comment]
@bochecha that was to picture the fact that ideascube wouldn't fail.

On a sidenote, everything should return an exit value. My cat does!
