### ISSUE TITLE
Ideascube catalog : Build library.xml file from ZIM and Index

### ISSUE THREAD

**Issue by fheslouin** [ideascube/ideascube#360]
Currently the Ideascube catalog works as fallowing : 
1. Add a remote catalog
2. Download a ZIP file containing a ZIM and Index directory in Ideascube cache folder
3. Unzip everything, move ZIM and Index to Kiwix folder and build an library.xml file

In the KoomBook context we won't have enough space to stock the ideascube cache folder and the kiwix folder, this represent twice the space for a unique ZIM project...Furthermore this is taking a lot of time to download everything from kiwix server each time. 

We set up an Ideascube cache server with all the ZIM and Index pre-loaded. We copy each time we need the ZIM and Index on the KoomBook hard drive. However we have to build manually the library.xml file which is not really efficient. 

What we could do : 
1. Ideascube catalog scan a specific folder for a ZIM file and an Index directory
2. Build a library.xml file from those file and folder 
3. Ideascube catalog do this for each ZIM project

This will prevent from unpacking the cache folder directly on the KoomBook which take a lot of time and resources.

**Comment by yohanboniface** [comment]
Kiwix sprint this month should add the index inside the ZIM itself. This will simplify a lot the install process. So I'd say let's see how the sprint goes before trying to change the workflow.

**Comment by yohanboniface** [comment]
cc @mgautierfr :)

**Comment by bochecha** [comment]
> Kiwix sprint this month should add the index inside the ZIM itself. This will simplify a lot the install process. So I'd say let's see how the sprint goes before trying to change the workflow.

Agreed.

Especially, we might not even need to download zips any more once the index is inside the zim, the zim file would be enough.

That would save roughly 200MB from each downloaded archive: that's the weight of the compiled kiwix application for Linux, Windows and Mac.

**Comment by fheslouin** [comment]
Great, if I understood well ideascube catalog will download directly the ZIM + Index and install it into the kiwix folder, I guess ideascube will generate the library.xml automatically. 

We should be able then to copy manually a ZIM file from an hard drive to an other and run ideascube to build the library.xml file

Could think about a way to add automatically a card on ideascube homepage ?
