### ISSUE TITLE
Shorter name in media-center

### ISSUE THREAD

**Issue by fheslouin** [ideascube/ideascube#362]
![capture du 2016-06-14 10 47 57](https://cloud.githubusercontent.com/assets/3833063/16036753/90a741cc-321d-11e6-9ee4-f40ee2362d29.png)
Sometime the name is too long and break the CSS grid.

We could also remove underscore and dash as it does not look so nice

**Comment by yohanboniface** [comment]
Garbage in, garbage out ;)
