### ISSUE TITLE
Order medias in mediacenter by date or name

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#363]
Medias in the mediacenter are ordered by last creation date. This is not always relevant. It could be useful to allow the user to choose to order medias by name or by date, in the list pages.

**Comment by barbayellow** [comment]
Is it something we can do with the new verison of the mediacenter ?

**Comment by barbayellow** [comment]
Is it something we can do with the new verison of the mediacenter ?

**Comment by yohanboniface** [comment]
> Is it something we can do with the new verison of the mediacenter ?

The new version does not change anything on this side, but it should not be that hard to implement.
