### ISSUE TITLE
Media center bug on tag and page

### ISSUE THREAD

**Issue by fheslouin** [ideascube/ideascube#364]
On the media center, while being on page 2 or 3, selecting a tag raise the following error
```
Page not found (404)
Request Method: 	GET
Request URL: 	http://koombook.lan/es/mediacenter/?tags=orinoco&page=2
Raised by: 	ideascube.mediacenter.views.Index
```
This error does not occur on page 1

**Comment by yohanboniface** [comment]
OK, I guess this is because the page parameter is kept.
I'll try to fix that today!
