### ISSUE TITLE
Checking  or adding an item in the stock list lacks of convenience

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#369]
When creating a new [inventory](http://ideasbox.lan/fr/monitoring/stock/inventory/) to list periodically every items available in the box, adding an item or validating an item reload the page and send the user back at the top of th page. It's not a bug but it's not really convenient since the list f all available items is quite long. Maybe a link to anchor in the page could be a solution ?

![stocklist](https://cloud.githubusercontent.com/assets/4816690/16361442/a2a5feae-3b91-11e6-8861-c8c2420a078c.png)

**Comment by yohanboniface** [comment]
Are you entering barcodes in the top form?

**Comment by barbayellow** [comment]
Usually we do. this "inconvenience" occurs only when we use the mouse to click manually on the big red buttton (and the "plus", "minus" or "remove" button) in the stocklist which is something we do sometimes.

**Comment by yohanboniface** [comment]
OK. I guess we may enter in the Ajax area at some point ;)
