### ISSUE TITLE
Wifi module : Issue on accented character on hotspot list

### ISSUE THREAD

**Issue by fheslouin** [ideascube/ideascube#372]
Ideascube raise an issue when trying to list an hotspot with accented character (ex : Chloé WP)
Traceback : http://dpaste.com/14A4YF2

**Comment by bochecha** [comment]
I have a hunch, and it's something I really don't want to have to fix...

What system are you running this on?

**Comment by bochecha** [comment]
So just to be 100% sure, on that Koombook where you had the problem, can you run the following in a Python shell:

```
>>> import sys
>>> sys.byteorder
```

What does it return?

**Comment by bochecha** [comment]
And one more question: what was the system locale on that koombook?

**Comment by bochecha** [comment]
So @fheslouin confirmed the Koombook is little-endian, just like the Jessie machine I have here to test things.

However, I can't reproduce the problem. :confused:
