### ISSUE TITLE
Display cards for installed packages

### ISSUE THREAD

**Issue by yohanboniface** [ideascube/ideascube#375]
Challenge: define how to group cards (for example to group all wikipedia packages (by language) in the wikipedia card).

**Comment by mgautierfr** [comment]
In the catalog specification we've made a kiwix hackathon (http://www.kiwix.org/wiki/Catalog), we've had a 'content_group' attribute for this case.

**Comment by yohanboniface** [comment]
Very quick and rough follow up after backlogging on IRC:
- I suggest in a first time we do not add a card model
- we want a dedicated Setting that will only store card ids (and certainly a boolean status)
- every content package (even the media center ones) when installed will register itself as card (so appending its id to the dedicated setting)
- a staff user can then decide to show/remove a card (by changing its status in the setting)
- we don't have submenus anymore in the cards
- I suggest in a first time we do not are about cards order: they are in the order they have been installed; we'll see in a later step to let the user reorder them
- card contents are all in HTML files, and if no dedicated HTML exist for the given id, we use the package metadata with the generic HTML template, more or less like today
- we only are talking about package content related cards: admin and system cards will still be only in settings files for now

Moving to the airport now! :)

**Comment by mgautierfr** [comment]
This is not so simple :)

There is several things needed to correctly render a cards:
- The name of the package itself (wikipedia_en, wikipedia_fr, wikibook_en, france.maps)
- The name of the card (ie, the name of the html template to use) (wikipedia, wikibook, maps, ...)
- Data that need to be used by the template (lang, url (that may be constructed at rendering), name)

At first look, we can say that we can infer the two latters from the first one and that is.
However, let's see how the card rendering is made :
Cards in the config are "complex" object (dict), that may contains an 'id' (defaulting to 'custom' if not present). This id is used as the card template name to use.
What you propose is that we store in the settings another dict object that behave differently (there are the id of the package to use (not the card template name), and a boolean to display it or not).

But, as we want to keep old admin and system cards, we have to handle the two different dict nicely, at choice :
- In the index.html template. If the dict as a package_id, ask the catalog for the package metadata, look in that metadata which template to use, render this template. Else check for 'id' and render this template, 'else' ... This seem to me a bit to complex for a html template. And error prone (what if a admin template has a 'package_id' metadata ?)
- Do not change the index.html and reconstruct a correct card dict from the 'card_package_settings' dict in the view. Thus, we get a string from the settings db, json parse it to get a complex object ... and recreate another complex objects cause the ones we've got are not what we need.
- Put directly the dict we want in a list in the settings (less work at rendering, no request to the catalog). 
- Put directly the dict we want, not in a json list in the settings, but in the db.
- Another ?

I was already implementing the last point. But yes, maybe I'm going to quickly and we can do without a card model in the db. (But, first solution seems to me too quick&dirty).

There is also two points to mention:
- There is no notion of package in the db. So all requests to get metadata of a package go through the catalog. This means that we create a catalog instance, at least, a each rendering of the index.
And each catalog instance creation means io to read the cache/remotes/install_packages informations from the yml.
- I'm not fan of storing complex objects in the settings db. If we store a list of dict of information about the cards to display, what is the type of the setting ? List, List of dict, List of dict with a string and a boolean ? This structure **will** change, how do we handle migrations ?

Having a database model, django can help us for migration.
However, I agree it is not perfect. Each card may need different information to render correctly. How do we handle this ? Do we add a optional field for each information a card may need ? I used a Json field, but it make django migration script a bit more complex.

As I said : this is not so simple.
Ideas are welcomed.

**Comment by mgautierfr** [comment]
See the WIP branch package_card_auto (and the commit messages)

This branch follow the second proposition of my former message.

There are a lot of dependencies on the catalog module (In the index, mediacenter view, search, ..)
Not sure it's a problem right now, but we should find a way to decouple module, and try to cache useful information (instead of creating a catalog instance each time)

For your proposition, ybon, to have the settings also pointing to admin and system cards, I think the simplier is to add a id to the cards in the config, add the ids of the cards we want to display and let the function build_package_card_info look in the config to rebuild the cards info.

Missing:
 - Tests
 - A way to the user to remove or add cards.

**Comment by bochecha** [comment]
Wasn't this fixed by #436?

**Comment by yohanboniface** [comment]
Closing here, we'll open dedicated issues where/when needed.
