### ISSUE TITLE
Build failling with new Pillow

### ISSUE THREAD

**Issue by yohanboniface** [ideascube/ideascube#408]
https://paste.gnome.org/pglmszxiy

Workaround: downgrade it
Solution: find a way not to use wheels for compiling, should be passing `--no-binary` to pip.

**Comment by bochecha** [comment]
The proper solution will be to pass `--no-binary` to pip, as you said.

This requires dh-virtualenv >= 0.8, which introduced the `--extra-pip-args` option, allowing us to do that.

Unfortunately, Jessie only has dh-virtualenv 0.7.

Fortunately, Jessie backports contain dh-virtualenv 0.10.

I'm [trying to figure out a way to have our build system depend on packages from the backports archive](http://unix.stackexchange.com/questions/298001/building-with-sbuild-and-backports), without success so far.
