### ISSUE TITLE
New card "out of the box"

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#414]
We need a new kind of card on the home of ideascube : a direct access to the website of the ideascube community : http://www.ideas-box.org/index.php/fr/communaute. This website is available in English, French, Spanish and Portuguese. Ideally, depending on the ideascube context and the selected language, the user is redirected to the relevant language. Default being English.

Since this is a website, we would need to hide this card if there is no Internet connection. This feature could be useful for some other website : display or not a card depending on the Internet connection.

**Comment by bochecha** [comment]
> Since this is a website, we would need to hide this card if there is no Internet connection.

That seems like a recipe for confusion.

« I swear, I saw this button yesterday but it's gone today! »

Probably better to find a clear way to indicate that this is online content and that it's not available when there is no Internet connection?

**Comment by yohanboniface** [comment]
> Probably better to find a clear way to indicate that this is online content and that it's not available when there is no Internet connection?

Agreed that it's not easy to solve in UX point of view, but just want to add that  I think "there is not internet connection" is not a concept that easy to understand for people while they are on their browser, running on a website, etc. (the ideascube site). The difference between the local network  and the Real internet is really not easy to catch during training ;)

**Comment by barbayellow** [comment]
This is a tough one... Ideally we should include cards linking to website on the Internet only when we do know we have an Internet connection where the ideas box is deployed. That could contain the confusion effect.

**Comment by yohanboniface** [comment]
We need a wording and an icon (or even a more custom design while it fits in the card logic), can you deal that @barbayellow ?
