### ISSUE TITLE
Generate "latin written name" from "full name" input

### ISSUE THREAD

**Issue by yohanboniface** [ideascube/ideascube#418]
In non latin writting countries, the user form contain a "latin written name".
Now they are written by hand, and it takes time for people not used to write in this alphabet.
We could generate it from "full name" with `unidecode` module.
Not sure we have a way not to generate it for already latin written name, but that's not a big issue at the end.

**Comment by bochecha** [comment]
I'm curious, why do we need a romanization of people's names?

In any case, I've been having much joy from [python-slugify](https://github.com/ideascube/ideascube/issues/118#issuecomment-225360759)

**Comment by yohanboniface** [comment]
> I'm curious, why do we need a romanization of people's names?

Not really use about where in the process, but it's about non fluent Arabic people dealing with the data. Even in the camp here there is many people from the hum staff that can't deal with written Arabic.

> In any case, I've been having much joy from python-slugify

We already have unicode as a deps. Do you think it's worth switching?
