### ISSUE TITLE
A command-line tool to manage in-database settings

### ISSUE THREAD

**Issue by bochecha** [ideascube/ideascube#440]
That would be nice, to manage the boxes properly.

It would have several benefits:

* manage the settings from ansible
* introduce experimental settings/behaviours that we wouldn't expose in the UI at first, giving us some time to test them in the field, eventually exposing them in the admin UI later on

I'm thinking of something like the `gsettings` tool in GNOME:

```
$ ideascube settings get content.local-languages
['ar', 'en', 'es', 'fr']
$ ideascube settings set content.local-languages ['en', 'zh-hant']
```

I would think the desirable features would be:

* `settings get <namespace>.<key>` to get the value of a setting
* `settings set <namespace>.<key> <value>` to set the value of a setting
* `settings list` to get the list of setting namespaces
* `settings list <namespace>` to get the list of setting keys in a namespace
* `settings reset <namespace>.<key>` to reset a setting to its default value
* `settings help <namespace>.<key>` to obtain help on a setting (description, possible values, default value)

The first two wouldn't be too hard to implement right now.

However, the other ones are a bit more tricky, as we currently don't have any of the information they would need anywhere.

So we'd need some kind of a registry for the settings...

It's starting to look like [we should move the settings management to its own app](https://github.com/ideascube/ideascube/issues/441).

**Comment by barbayellow** [comment]
I love the ideas : being able to manage settings via ansible and having the ability to test new features. So :+1:
