### ISSUE TITLE
Don't let staff lock themselves out

### ISSUE THREAD

**Issue by bochecha** [ideascube/ideascube#443]
I just realized I could remove the staff status from my user.

So I tried it. :)

Of course, that was the only user on the system, so now there's no more staff user.

Sure, when I try opening a page at that point, I get prompted to create a staff user, but it would probably better to not let staff remove staff status from the only staff user in the first place.

I assume that when creating the first staff user (i.e booting to Ideascube for the first time), nobody is connecting to the app yet, so the first staff creation is relatively safe.

However, once the thing has been deployed for some time, and people connect to it, I could imagine a nasty race between the staffs rushing to create a new staff user after locking themselves out, and the users who would be asked to create one (and might comply even without bad intentions).

**Comment by yohanboniface** [comment]
:D
