### ISSUE TITLE
Migrations broken on servers having run previous migrations after #429

### ISSUE THREAD

**Issue by yohanboniface** [ideascube/ideascube#456]
http://paste.ubuntu.com/23116110/

The workaround is to run a reindex (that will crash but create the idx table anyway), than a migrate again.

We need a way to fix this for installed servers.

One option may be to have a pre-migrate that create the idx table.

**Comment by yohanboniface** [comment]
To reproduce:
- remove any db in storage/
- git checkout 0.5.0
- python manage.py migrate
- python manage.py dummydata
- git checkout master
- python manage.py migrate

This should fail with the current HEAD, and we should find a way to fix this scenario.

**Comment by bochecha** [comment]
I can't reproduce, because the `dummydata` step fails here... because the code at the time wasn't Python3 compatible :D
