### ISSUE TITLE
Catalog: prevent adding twice the same remote

### ISSUE THREAD

**Issue by yohanboniface** [ideascube/ideascube#459]
I managed to add twice the same remote URL, I think (and thought we were already actually) we should prevent that.

```
(1:518)$ ideascube catalog remotes list
IDEASCUBE_ID=idb_jor_alhashmi
Importing settings from ideascube.conf.idb_jor_alhashmi

          [Kiwix] Kiwix ZIM content : http://catalog.ideascube.org/kiwix.yml
[OSMybon] Experimental OSM Maps catalog : http://catalog.yohanboniface.me/catalog.yml
                        [maps] Maps : http://catalog.yohanboniface.me/catalog.yml
```

**Comment by bochecha** [comment]
Indeed, what was done is this: 5eaeeffdc4f5af07456e3cf42c043f583912238a

> If we try to add a remote already existing (same id) with same url, print a warning.
> If we try to add a remote already existing but with different url, raise as usual.

Fixing.
