### ISSUE TITLE
Add a favicon

### ISSUE THREAD

**Issue by yohanboniface** [ideascube/ideascube#466]
Browing uwsgi logs now:

[pid: 1116|app: 0|req: 11/20] 192.168.2.141 () {32 vars in 441 bytes} [Mon Sep  5 11:09:42 2016] GET /favicon.ico => generated 2276 bytes in 85 msecs (HTTP/1.1 404) 4 headers in 133 bytes (1 switches on core 0)

Having a favicon is user friendly.
And then we should make nginx serve it.

@barbayellow giving the issue to you to have a graphic designer work on this (for ideasbox, koombook and a default ideascube one I'd say).

Related #302

**Comment by yohanboniface** [comment]
BTW, given we are only targeting modern browsers, I think we could add a `meta` tag so we could locate the favicon under /static/ so Nginx will serve if without the need for a dedicated rule. Something like:

    <link rel="Shortcut Icon" href="{% static 'favicon.ico' %}" type="image/x-icon">

**Comment by barbayellow** [comment]
Deal! Our graphic designer is coming back from holidays in the coming days.

**Comment by yohanboniface** [comment]
Cool. Let's try to have at least a first version this week: this may reduce a lot the connection handle by the server (by caching it on client side).

**Comment by bochecha** [comment]
@barbayellow Did you graphic designer get any time to work on this?

For the record, right now we have the following favicons:

* Ideasbox: https://github.com/ideascube/ideascube/blob/master/ideascube/static/ideascube/img/favicons/ideasbox.png
* Koombook: https://github.com/ideascube/ideascube/blob/master/ideascube/static/ideascube/img/favicons/koombook.png

They aren't super pretty (you can see my bad graphics skills :wink: ), so your graphic designer probably could do better. :smile:

**Comment by barbayellow** [comment]
Not yet sorry. But I'll put this one on the top of the stack (not sure if we can say this I'm English but you get the idea :)
