### ISSUE TITLE
Stock app : labels and language

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#472]
In the stock app, in the [demo ideascube](http://demo.ideascube.org/fr/monitoring/stock/item/1/edit/), the labels are in Spanish even though the selected language is different. So that means that we have weird labels "Nombre" that means name in Spanish and has a different meaning in French. It's confusing.

![colombia - mozilla firefox_001](https://cloud.githubusercontent.com/assets/4816690/18321262/82b9c7d0-752d-11e6-9096-9b3d53fd0080.png)

Cf screenshot

**Comment by bochecha** [comment]
This seems to have been fixed by #517
