### ISSUE TITLE
User app : labels

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#473]
The serial label is not very self explaining. Maybe "Nickname" or pseudo could be used ?

![colombia - mozilla firefox_002](https://cloud.githubusercontent.com/assets/4816690/18321321/bd4aac7a-752d-11e6-8d35-b84a407a81bf.png)

**Comment by yohanboniface** [comment]
This field is usually used for the number from the user card.
But yeah, let's try to avoid using "serial" when there is not user card.

**Comment by bochecha** [comment]
That field is now displayed as "Identifier" since 38f5c4d.
