### ISSUE TITLE
Responsive design for the forms

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#474]
When the sreen is resized, the user interface is less usable. Since many projects include tablets, this is something that is important to improve.

![colombia - mozilla firefox_003](https://cloud.githubusercontent.com/assets/4816690/18321451/50bd2f0a-752e-11e6-8219-8fac9158fa87.png)

**Comment by yohanboniface** [comment]
We also need to add those buttons in the bottom of the form.
Maybe we can keep them both on the top right and on the bottom, and hide (with `thide` or `mhide` class) them when the screen is small.

**Comment by barbayellow** [comment]
From a ui perspective, having twice the same buttons on the page is confusing. Having the buttons at the bottom of the form just once sounds as a good idea.
