### ISSUE TITLE
Add several media to one media-center entry

### ISSUE THREAD

**Issue by fheslouin** [ideascube/ideascube#483]
We had recurrent questions about the way to had several media to one media-center entry. 
For instance, we can have an audio file link to a pdf file or several versions of a same software (for windows, mac, linux). Currently we have to make one post per file which is not really convenient.

Could we find a way to create this feature ?

**Comment by yohanboniface** [comment]
Can't we use packages for that?

**Comment by fheslouin** [comment]
That could be a way. However I don't know exactly how the packages will be display...
