### ISSUE TITLE
The Library app and the stock application should be able communicate

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#484]
Problem : the stock app and the library app do not communicate. When a new item is entered in the stock app, if the new item is a book, we should be able to enter the ISBN code or to establish a kind of connection with the already mass imported notices.

**Comment by yohanboniface** [comment]
Agreed!
We may merge BookSpecimen into Stock specimen, but not easy.
(Or just provide some helpers to fulfill ones from the others.)

**Comment by barbayellow** [comment]
Some helpers could be a fist step.

**Comment by barbayellow** [comment]
Since BSF plan to use Omeka to handle every digital or physical content within the Ideas Boxes, the books notices will be stored in Omeka. So I wonder if we should invest time in the fancy or out of date notice import protocol such as unimarc or Z3950 since we could load them directly from Omeka. At least for BSF needs. For any other needs, having an automatic import of the books notices is useful.

We should also think to integrate openlibrary.org in our work-flow. We could for instance export the library from omeka to openlibrary.org and choose to push the notices from omeka or from openlibrary.

This is an open discussion.

**Comment by yohanboniface** [comment]
Closing, this a been done and released.
Let's open new issues for further needed iterations when they comes out.
