### ISSUE TITLE
The catalog remote file format should be (more) compatilbe with the "Esino" catalog specification.

### ISSUE THREAD

**Issue by mgautierfr** [ideascube/ideascube#487]
During the kiwix sprint at Esino Lario, we defined a catalog specification for the metadatas associated to a package : http://wiki.kiwix.org/wiki/Catalog

At a point, we will make ideascube compatible with the Esino specification.
We should start to slowly change the way we name things in ideascube to be more compatible with the
Esino specification and so reduce the gap.

This issue is here to open a discussion to decide how we do thing. (And as a remainder for the future)

Here a first sight of the differences between the two catalog specifications :

| Ideascube | Esino | Comments |
| --- | --- | --- |
| id | id | Some bsf catalog has id in there metadata |
| key | name | The 'keys' in the bsf yaml files are used as name in ideascube. However, it doesn't follow the exact same semantic than Esino spec* |
| version | version |  |
| name | title | We could simply rename the 'name' attribute to 'title' |
| description | description |  |
| language | languages | Only one in ideascube, may contains more languages in Esino (ISO 639-3) |
| sha256sum | checksum | It has been proposed to rename checksum to sha256sum in Esino to explicit that we use sha256 for the checksum. Maybe nothing to do on our side. |
| url | url |  |
| size | size |  |
|  | mimetype |  |
| type | intended_use | Names let us think it is not the same, but we use it for the same thing : How to use the content. |
|  | thumbnail_urls | To be defined in (in Esino as in ideascube) |
|  | requires |  |
|  | tags |  |
|  | extra_fields |  |
|  | content_group | Could be used by ideascube to define how we display cards. |
|  | variants |  |
|  | altenate_urls |  |
|  | authors | Could simply be added to the ideascube metadata |
|  | publisher | Could simply be added to the ideascube metadata |
|  | packager | Could simply be added to the ideascube metadata |
|  | licences | Could simply be added to the ideascube metadata |

\* The name in Esino follow the `source.resource_name.variants` format (the lang potentially being part of the resource_name)
At bsf we follow the `name.lang` format.

**Comment by bochecha** [comment]
> sha256sum 	checksum 	It has been proposed to rename checksum to sha256sum in Esino to explicit that we use sha256 for the checksum. Maybe nothing to do on our side.

I'm **strongly** opposed to renaming `sha256sum` into `checksum`. Using `checksum` would make it extremely hard to move to a different hash function.

I've been there with Fedora, it took me two years to get the migration from md5 to sha512 right, because it took tons of preparatory work in various stages.

> type 	mimetype 	May be type but it seems we do not use it in ideascube.

Those two are completely unrelated. `type` is an ideascube-specific thing, it lets us know the `Package` subclass to use. No, that's not really great.

> handler 	intended_use

We don't use the `handler` key any more in Ideascube. It was meant to let us pick the appropriate `Handler` subclass, which was bad, and is now entirely done by the `Package` subclass. (see `type`)

> key 	name 	The 'key' in the bsf yaml files are used as name in ideascube. However, it doesn't follow the exact same sementic than Esino spec*

We also have quite a few assumptions in the code based on the format of the name. Those assumptions are probably wrong and we could/should fix them, but I'm just mentioning this to remember that moving to the same semantics as the Esino catalog (your footnote) is not trivial. :smiley:

**Comment by mgautierfr** [comment]
> I'm strongly opposed to renaming sha256sum into checksum. Using checksum would make it extremely hard to move to a different hash function when (not if!) the current one ends up being broken.

Yes, and it is the contrary that is proposed :)


>> type mimetype May be type but it seems we do not use it in ideascube.

> Those two are completely unrelated. type is an ideascube-specific thing, it lets us know the Package subclass to use. No, that's not really great.

 >> handler intended_use

> We don't use the handler key any more in Ideascube. It was meant to let us pick the appropriate Handler subclass, which was bad, and is now entirely done by the Package subclass. (see type)

I've mixed the name. You're right, it is the `handler` that is not used by ideascube and the `type` that corresponds to the `intended_use`. I will change it in my first comment to avoid misunderstanding.

**Comment by bochecha** [comment]
>> I'm strongly opposed to renaming sha256sum into checksum. Using checksum would make it extremely hard to move to a different hash function when (not if!) the current one ends up being broken.
>
> Yes, and it is the contrary that is proposed :)

I know, and I was stating why that proposal is the right thing to do and we should not budge on this point.

**Comment by yohanboniface** [comment]
I think we should move forward quickly in those aspects:
- replacing `name` by `title`
- use `source.content.variants` scheme for our id (which is the name in Esino)
- replace `language` by multivalued `languages`

**Comment by yohanboniface** [comment]
About `checksum`, I'm tempted to suggest we keep `checksum` and include the algorithm used in the value, like `checksum: "sha256:xxxx"`, so the catalog consumer knows which key to use. We also may decide that if no algo is given in the value, it's sha256. Just brainstorming here.

**Comment by barbayellow** [comment]
Reminder : we will need this year (2017) to work hard on the catalog. In the perspective of its separation from ideascube, maybe we could start to think again to the esino lario specs. This is just a "up" comment.
