### ISSUE TITLE
Library app does not display created books

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#491]
In the library app of the demo server http://demo.ideascube.org/fr/library/  I have entered 3 books as an admin. I can see those when I am connected as an admin but I can't see them when I am disconnected (ie as a regular user). This server is configured to use Spanish as the main language, the books have been entered in French.

**Comment by yohanboniface** [comment]
It's because they are missing specimen, I think.
Regular users only books with specimen.
