### ISSUE TITLE
Plug ansiblecube to ideascube CI

### ISSUE THREAD

**Issue by fheslouin** [ideascube/ideascube#501]
It would be nice to to have some test on code pushed to ansiblecube repository. 

For instance, check : 
- Yaml syntax
- Json syntax
We are going to be 3 pushing regularly and for sure, we will make some mistake...

**Comment by bochecha** [comment]
This should have been in ansiblecube, not in ideascube. :wink:

Closing, since I've got https://github.com/ideascube/ansiblecube/pull/39
