### ISSUE TITLE
Resize images on upload

### ISSUE THREAD

**Issue by yohanboniface** [ideascube/ideascube#51]
I don't think we need book covers bigger than, say, 300px height, maybe 500px to take a bit of margin.
So I suggest to resize them on upload, if they are bigger than that.

This also applies for media center and other image concerned modules.

**Comment by vinyll** [comment]
Some libraries that may do the job:
- https://github.com/mariocesar/sorl-thumbnail
- https://github.com/SmileyChris/easy-thumbnails
- https://github.com/vinyll/django-imagefit
