### ISSUE TITLE
Update installed metadatas on catalog cache update?

### ISSUE THREAD

**Issue by yohanboniface** [ideascube/ideascube#513]
So, here we are in the dynamic cards worlds, and that's nice.

We can yet see some issues, though, because the metadata of the packages are not really ready for end user (titles too long, useless description…).
I think we need a way to keep those metadatas up to date in the servers when a catalog is updating them (for example we make a better description or, later, we add a new localized description or name).

I'm not sure how we can handle that properly, as there are a bunch of edge cases around. For example, we may want to update the name or description of an already installed package, but we certainly do not want to change it's size or sha. And we can even have cases were we'd prefer not to update the description (for example the description describe a new feature that is not yet in the old version of the package, currently installed).

In the same time needing to reinstall a package just because there is a typo in the name or description or because we need a new localization or the icon has changed is not a good workflow.

So let's try to have a thread on how to deal with that.

**Comment by yohanboniface** [comment]
Idea: have a command that update all the metadatas when the sha256sum has not changed; and does not nothing when it changed. That should cover the main needs imho.

**Comment by bochecha** [comment]
> Idea: have a command that update all the metadatas when the sha256sum has not changed; and does not nothing when it changed. That should cover the main needs imho.

We don't need a new command for this.

When updating packages, we decide that there is an update if anything changed in the metadata for this package: Idea: https://github.com/ideascube/ideascube/blob/master/ideascube/serveradmin/catalog.py#L738-L740

Instead, we should do that if the version is still the same. (and print a big error message if the version is the same but the sha256 changed)

If the version and sha256 didn't change, then we can just overwrite `self._installed[pkgid]` with `self._available[pkgid]`.

And we do that automatically, and always.

And just like that, `ideascube catalog update` fixes the bad metadata without reinstalling the same package.

**Comment by yohanboniface** [comment]
That's a nice idea, but maybe it's better to be more explicit. This would be a bit like an hidden behaviour of `update` that usually does something else.
Plus we may have situations where we want to change all the metadatas but not update any package (because we don't have bandwith enough for exemple), and running `ideascube catalog update` will actually update any package that have a new package candidate.

**Comment by bochecha** [comment]
> This would be a bit like an hidden behaviour of update that usually does something else.

Or you could consider it improves the current update behaviour.

For example, currently, `ideascube catalog update` could downgrade a package, if the version available in the remote is lower than the one currently installed.

> Plus we may have situations where we want to change all the metadatas but not update any package (because we don't have bandwith enough for exemple)

This is a good point.

I've been thinking for a while that we should have a `--disable-download` option. It would be useful to make sure that we install/update packages from the specified additional cache.

It would also fix this issue.

**Comment by yohanboniface** [comment]
> I've been thinking for a while that we should have a --disable-download option. It would be useful to make sure that we install/update packages from the specified additional cache.

That option would be nice (nit: I'd call it `--no-download`), but I think it will not cover the need here: we are not keeping the cache on the servers atm.
