### ISSUE TITLE
order by is not translated

### ISSUE THREAD

**Issue by Narjis89** [ideascube/ideascube#516]
here is a screenshot of the page where it appears 
![screenshot from 2016-10-03 17-07-23](https://cloud.githubusercontent.com/assets/22523541/19040366/700f74cc-898c-11e6-8e0e-8e77c29acf25.png)

**Comment by yohanboniface** [comment]
Fixed in last release, thanks to you @Narjis89 :)

**Comment by Narjis89** [comment]
thanks :)
