### ISSUE TITLE
Displayed packages in server upgrading to auto cards

### ISSUE THREAD

**Issue by yohanboniface** [ideascube/ideascube#519]
At the moment, when upgrading a server to the new automagical home cards, none of the installed packages are displayed.
This is an issue for all the servers we update remotely without anyone able to do the change from the new admin page.
We need a way to make that automatically.
Here are some options:
- add a dedicated management command that full in the setting
- make that when no card is selected at all, we display all (but UI hard to deal with)
- have a `postinstall` subcommand for the catalog, to replay the postinstall step on the already installed packages
- adapt `catalog list --installed` to have a script friendly output that can then be used by ansible to then set the good setting

Let's discuss this next meeting.

**Comment by mgautierfr** [comment]
Fixed by @bochecha's commit d6a6b4 by adding a dedicated managament command.
