### ISSUE TITLE
Hide backup links

### ISSUE THREAD

**Issue by yohanboniface** [ideascube/ideascube#524]
Backup can only crash the server by totally fulling in the disk, so it's very risky to keep it.
Let's remove the links (cards and server admin index link) until we totally switch to content packages, and then we'll reenable them again.

**Comment by fheslouin** [comment]
I agree, the homepage is filled up with enough links, I think it confused the end user.

**Comment by fheslouin** [comment]
We can remove the link from the admin menu as well
