### ISSUE TITLE
Scheduled shutdown

### ISSUE THREAD

**Issue by vinyll** [ideascube/ideascube#532]
A feature request was to enable a shutdown at a configurable time.
The interest is to make sure one does not forget to switch it off in the evening and runs out of battery.
A side effect might be that adminsitrator leave the habit of shutting down the computer from the interface and accidentally switch off the generator without prior manual shutdown of the computer.

Opinions are welcome.

**Comment by bochecha** [comment]
Ideascube moved to Framagit.

This issue has been migrated.

Please continue the conversation there:

https://framagit.org/ideascube/ideascube/issues/532
