### ISSUE TITLE
Catalog: DownloadCheck.checksum_mismatch

### ISSUE THREAD

**Issue by yohanboniface** [ideascube/ideascube#534]
From time to time the download fails in the middle:

```
ideascube@idb-jor-zaatari-52:~$ sudo ideascube catalog install tedscience.en
IDEASCUBE_ID=idb_jor_zaatari
Importing settings from ideascube.conf.idb_jor_zaatari

Download: 45.17% |⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛                                                           | 5.2 GiB/11.4 GiB (377.3 KiB/s) | ETA: 05:07:01Failed downloading tedscience.en
DownloadCheck.checksum_mismatch
```

Not sure what can cause such an error in the middle of the download. Seems like, for some reason, somehow we consider that the dl is finished and then do a checksum, which of course cannot be correct.

**Comment by letompouce** [comment]
Looks like in Colombia we have a chance to reproduce :)
