### ISSUE TITLE
Manage services 

### ISSUE THREAD

**Issue by fheslouin** [ideascube/ideascube#557]
An other confusing link is : "Manage services", I think we should remove it as it is useless so far.

**Comment by bochecha** [comment]
Why is it useless?

Doesn't it work?

**Comment by fheslouin** [comment]
Personally I never taught anybody to use this feature. I think most of the box or koombook manager does not know what is nginx, kiwix or uwsgi and won't know what to do if there is something wrong on the webpage (should I restart nginx or uwsgi ??). 

I think it is worth disabling this link and wait for cokpit

**Comment by bochecha** [comment]
Ah, then it's not useless, it is unused.

Cockpit won't change this much though, if people don't use it now, there's no reason they'd use it more in the future.

**Comment by fheslouin** [comment]
I don't say anything about this link as it is not really useful for the box manager. 

However use cokpit to change the AP password, IP, restart a service and so on will be worth to teach.

**Comment by bochecha** [comment]
> However use cokpit to change the AP password, IP, restart a service and so on will be worth to teach.

That's a completely unrelated ticket though. Please let's not mix everything.

**Comment by fheslouin** [comment]
True, I just wanted to illustrate how this feature could be more useful with a set of other features...
