### ISSUE TITLE
Digital specimen should be limited to one

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#560]
The number of [book digital specimen in the library](http://koombook.lan/fr/library/book/1/new-specimen/) should be limited to one. 

Having several specimen for one book makes sense (even if the creation process of the books and the specimen should be simplified), however, we should not be able to create more than one digital specimen for a book. The "specimen" concept does not really apply to the digital files.

**Comment by yohanboniface** [comment]
Why that? You can have one in pdf, one in epub, one in moby, and so on, no?

**Comment by barbayellow** [comment]
Agreed. L'êtes close this issue.
