### ISSUE TITLE
Link between stock and library app

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#566]
This links works but only from the library to the stock.
If you create a book and a specimen in the library app, the it is added in the stock.
However, if you create a book and a specimen in the stock app, it is not added in the library app. I don't know which solution would work the best. Some proposals : 
1. **Redirect** : adding a book or a specimen from the stock app should redirect the user to the relevant form in the library form (object or specimen). 
   Problem #1 : once you validate, you should be redirected to the stock app (using a post variable or anything relevant). 
   Problem #2, on a UI level, how do we deal with the generic button of the stock app that allows you to add an item in any module ? Should we redirect the user to the library form when he chooses to add a book ? Or just remove the generic button ?
2. **Disable book creation in the stock** : Book creation and specimen creation. But how do we deal with the modification ? Weird on a UI level. 

I would vote for the first proposal.

**Comment by yohanboniface** [comment]
I'm afraid in the stock we don't know that an item is a book :(

We may add a warning when adding an item to the "library" module (but not only books are added to the library module: also games…).
We may also have a dedicated module for only books.
But, whatever the solution we'll find, it will be limited: a user can still add book in the cinema module, etc.

I really agree that this situation is not ideal, but sadly I'm afraid there is no good solution around. Let's brainstorm anyway, inch Allah!
