### ISSUE TITLE
Time out on server backup

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#567]
Most of the time, since the backups are quite big files (300 Mo easily), when a backup is done from the web interface, we get a time out. This is confusing for the user because he might think that the bakcup is not complete. How could we deal with that ?

**Comment by yohanboniface** [comment]
See https://github.com/ideascube/ideascube/issues/131 https://github.com/ideascube/ideascube/issues/524 https://github.com/ideascube/ideascube/issues/541 ;)

**Comment by barbayellow** [comment]
sorry, I did not check for this one.
