### ISSUE TITLE
Remove the field "section" in the book creation form

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#574]
Isn't redundant, having 2 kind of categories for the books, _Section_ and _Tags_ ? Is the "section" really useful since there is no way for the user to browse the books by section nor for the staff to add or remove sections?

**Comment by yohanboniface** [comment]
Section is actually a requested field by "real" librarians, so let's keep it.
We may add a way to hide it at some point, but I think we are not there yet.
See https://github.com/ideascube/ideascube/issues/597 and https://github.com/ideascube/ideascube/issues/598
