### ISSUE TITLE
Add bibliotecamovil.lan

### ISSUE THREAD

**Issue by yohanboniface** [ideascube/ideascube#596]
In the Colombian project, we don't use "ideasbox", but "bilbioteca movil".
Given it's 20 box at once, we can consider it one of our main projects, and add `bibliotecamovil.lan` just like we have `koombook.lan`.
In an ideal world, this should not be hardcoded, but this is not a top priority, so make it simple for now, and concentrate is other tasks on our backlog.

**Comment by yohanboniface** [comment]
Watch out the OEmbed domain.

**Comment by bochecha** [comment]
Isn't that fixed by #611 ?
