### ISSUE TITLE
New book sections

### ISSUE THREAD

**Issue by yohanboniface** [ideascube/ideascube#597]
We want new book sections:
- children - myths and legends
- children - tales
- adult - myths and legends
- adult - tales

**Comment by yohanboniface** [comment]
Just wondering if we should not remove the "children/adult" from the section, and move it in tag instead.
I'm gonna discuss with the librarians here in Bogota.

**Comment by yohanboniface** [comment]
Fabio confirms that we needs children/adult, and furthermore gives us a table with their categories and the matching with ours when they exist:

![screenshot from 2016-10-27 14-29-01](https://cloud.githubusercontent.com/assets/146023/19782291/c2314388-9c52-11e6-8443-33f61ea69328.png)

**Comment by mgautierfr** [comment]
What is the difference between Historietas and Novela Gráfica ?
Google translate say me that historietas are comics.

**Comment by yohanboniface** [comment]
Well, it seems there is a difference according to the librarian way of cataloging, but as for now we will use only one category for both (comics).
