### ISSUE TITLE
Add colors to book sections

### ISSUE THREAD

**Issue by yohanboniface** [ideascube/ideascube#598]
Book sections are used to organize books in the physical library.
Each section should have it's own color, so the librarian can add colored stickers on the books with same colors.
What we want is to display the color near the section name in the dropdown select and when seeing the book page.

Fun fact: this is a request from the Colombian project librarians, but we used to have this in the very first version of the ideasbox.

Colors:
- novels: #4183D7
- poetry: #9B59B6
- theatre: #6C7A89
- documentary, digital, other, game: white
- comics: #D91E18
- cartoons: #e9d460
- myths and legends: #F27935
- tales: #4DAF7C
- graphic novels: #674172

**Comment by mgautierfr** [comment]
Those colors do not correspond to the color in #597.
Which one are the best ?

**Comment by yohanboniface** [comment]
The ones here.
