### ISSUE TITLE
Add "section" filter in library

### ISSUE THREAD

**Issue by yohanboniface** [ideascube/ideascube#599]
This means also indexing it, but we don't have a column for that.

**Comment by mgautierfr** [comment]
Does the kind column (only used by media for now) could be used for the section in library ?
The section ('adults - novels') is somehow the kind ('a novels for adults') of the book.

It would avoid us to add a new column in the search. 
But it may interfere with future improvements (as handling DVD or board games)

**Comment by yohanboniface** [comment]
Both your suggestion and your remarks are good :)
And as by recent discussions, it seems possible to have DVDs and games in there.
