### ISSUE TITLE
Non-book content in the library app

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#604]
We should add the the possibility in the library app to manage  
- DVDs
- Board games
- applications available on the android tablets with a short description

This is typically what regular librarians need and do !
Regarding the apps, this is not a physical items unlike books, Board Games and DVD. We could handle this as a notice without physical specimen.

**Comment by yohanboniface** [comment]
> We could handle this as a notice without physical specimen.

You may have the app for Android and for iOS. To me, this is the same as epub and/or pdf, so it's ok to use a specimen.

We may refactor the book creation so you can create both a book and a specimen in the same time, to address yours concern.

**Comment by yohanboniface** [comment]
We also may create dedicated models for Game, DVD, etc., because I feel it hard to have a generic model for those different objects.
