### ISSUE TITLE
add User.ethnic_group

### ISSUE THREAD

**Issue by yohanboniface** [ideascube/ideascube#609]
This one is a bit touchy, but here in Colombia knowing the ethnic group of people is requested by law, AND seen as a positive thing.
Though, AFAIK, this is illegal in France, so we may be sure we can then collect data on French servers.
May need a CNIL agreement or such.

cc @barbayellow this one needs cautious attention.

**Comment by barbayellow** [comment]
We'll check this one with our juridical department. I'm sure we should not activate this field in France.

**Comment by yohanboniface** [comment]
About the context, quoting Sergio:

> Here in Colombia, it is common when you work with vulnerable populations to ask about their self acknowledgement in regards to ethnic groups. This information is useful no just in terms of measurement but also makes easier   and more accurate the public and private interventions and strategies to support this populations. For example, it will not have the same effects the material and the contents of mobile public libraries in the coast of Colombia with afrocolombian populations than and intervention in el Cauca with indigenous communities such as the NASA or with peasants in rural zones in the center of the country. From this point of view, I strongly suggest we include this information in order to identify the communities we are working for and we can shape (as far as we can) our intervention. Also and in quantitative terms, due to our presence in isolated communities in colombia, we can contribute to the identification of the inhabitants in those territories.

**Comment by barbayellow** [comment]
BSF stands : 

- this is illegal in France and in Europe so we want to be sure that this feature will be only available for this project. 
- The activation of this field will be possible only through th configuration file. The gatekeepers will be the guys who will create the config file (ie BSF)
- The field will be name "extra" or "group". "Ethnic group" is not something we want to see in the code

**Comment by barbayellow** [comment]
After we talked with our partner, the field "ethnic group" is no longer needed. However, having a customizable extra field is something that can be useful for other projects, so let's keep it.
