### ISSUE TITLE
Admin UI 

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#631]
There is a weird behavior on the UI when you are logged as an admin. You need to click on "wifi" or "stop / start" to access the features allowing to admin the Koombook (choose the cards, change the names, change the language etc.). Anf whatever the button you click on, the user is served with the same page.

Wouldn't it be more logical to have just one card called "Parameters" with the classical roue crantée ?

**Comment by bochecha** [comment]
> You need to click on "wifi" or "stop / start" to access the features allowing to admin the Koombook (choose the cards, change the names, change the language etc.).

That's because those don't have a card to access them directly, they are only accessible from the navigation in the sidebar of other admin pages.

> Anf whatever the button you click on, the user is served with the same page.

That doesn't seem right. Each card on the home should lead to its own page. Which page are you reaching?

> Wouldn't it be more logical to have just one card called "Parameters" with the classical roue crantée ?

I've been saying this for a while now.

**Comment by mgautierfr** [comment]
>> You need to click on "wifi" or "stop / start" to access the features allowing to admin the Koombook (choose the cards, change the names, change the language etc.).

> That's because those don't have a card to access them directly, they are only accessible from the navigation in the sidebar of other admin pages.

There is a card for setting the displayed cards installed by packages. (If you are an admin)
If not, this is a bug.

**Comment by bochecha** [comment]
> There is a card for setting the displayed cards installed by packages. (If you are an admin)
If not, this is a bug.

It might not be in the config for the box @barbayellow is using?

**Comment by yohanboniface** [comment]
https://github.com/ideascube/ideascube/blob/master/ideascube/conf/kb.py#L7

**Comment by barbayellow** [comment]
I am not saying it is a bug, I am saying we should be more consistent and more logical. If you click on "wifi" you should only be able to set up the wifi options. However, our wifi page offers every administration options for a KB or an ideas box (or any "wifi", "start stop", "server name" or "home page" card). 

Maybe we should simplify and just add a "parameters" card for the admin that would allow a logged  user to change every settings of the IDB / KB. This is an open discussion.

**Comment by yohanboniface** [comment]
I see various points here:

- **whether to display an "admin menu" when you are in one admin detail page**: you seem to say we shouldn't, but #556 seems to say the opposite
- **if we blacklist one admin card (say "entries" in the koombook case), we should not display the link in the internal admin menu**:  I fully agree, this should be consistent
- **which "admin related cards" we should display on the home page**: my position here is that we should have a dedicated card for the day to day categories (users, entries, wifi?…), but I'd go for a more global "Advanced parameters" card for all the other admin related actions (managing server name, languages…), and then only have them in the internal admin menu

**Comment by bochecha** [comment]
Coming back to this after some time spent thinking about other things...

> which "admin related cards" we should display on the home page: my position here is that we should have a dedicated card for the day to day categories (users, entries, wifi?…), but I'd go for a more global "Advanced parameters" card for all the other admin related actions (managing server name, languages…), and then only have them in the internal admin menu

I've been pretty adamant since I started working on Ideascube that we should have a single "Admin" card, which brings the user to a sort of "control center" with all the admin features.

But now that I re-read what you wrote above, I'm starting to see things from a different angle, and I think there is some sense in what you're saying.

What you call the "day to day categories" are in fact not "settings". They are not configuration of the box. They are routine actions that staff must perform.

And as such, I do agree now that they should not be part of an admin/settings/"control center" section.

And that does mean (to me) that they shouldn't have the admin sidebar on the left, which is the opposite of what #556 asked for.
