### ISSUE TITLE
dpkg: error on post-installation

### ISSUE THREAD

**Issue by fheslouin** [ideascube/ideascube#639]
Migrating ideascube from 0.11.3 to 0.16 give an error on post-installation. 
It appear that the line https://github.com/ideascube/ideascube/blob/0a6362f18f12d4dcaa92a85cc24e0e5c7200ea9f/debian/ideascube.postinst#L37 return code 1 with message 
`Failed to execute operation: File exists`

This happen only in some case, I would suggest to use `-f`
                                                                                                                                            
```
# systemctl -f enable uwsgi.service     
Synchronizing state for uwsgi.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d uwsgi defaults
Executing /usr/sbin/update-rc.d uwsgi enable
Removed symlink /etc/systemd/system/multi-user.target.wants/uwsgi.service.
Created symlink from /etc/systemd/system/multi-user.target.wants/uwsgi.service to /etc/systemd/system/uwsgi.service.

```

**Comment by bochecha** [comment]
Huh? `systemctl enable` is a noop if the service is already enabled:

```
$ sudo systemctl is-enabled gdm.service 
enabled
$ sudo systemctl enable gdm.service 
$ 
```

If that really happens, then it would be a bug in Debian's systemd. 😨

**Comment by fheslouin** [comment]
Yep this is the normal behavior of systemctl, but it issue an error with uwsgi when file exist.

I'm gonna try to reproduce this issue to confirm the bug
