### ISSUE TITLE
Missing sudo as dependencies for post-install

### ISSUE THREAD

**Issue by swbsf** [ideascube/ideascube#647]
**sudo** doesn't seem to be a dependency for ideascube package :
`Paramétrage de ideascube (0.16.0) ...
Running migration
/var/lib/dpkg/info/ideascube.postinst: 24: /var/lib/dpkg/info/ideascube.postinst: sudo: not found`

Manually installing sudo fixes the issue.

**Comment by bochecha** [comment]
Already known, tracked as #297, and fixed by #341.
