### ISSUE TITLE
User import /export consistency

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#655]
In the users app, it's possible to import users from a csv file or to export users.
an export gives us a file with this column : 
date de création, |identifiant|extra|Disabilities (depending on the configuration of ideascube).
BUT when importing a file with the same columns and the same format, we get an error : "Invalid row at line 1: serial: * Ce champ est obligatoire". I've gtried with a column named "serial" and it works.
Shouldn't we have the same format in import and exit data ?

**Comment by bochecha** [comment]
That's because in your export, the `serial` field is called `identifiant`.

Do we actually translate the fields for the export? o_O
