### ISSUE TITLE
Can't log in with edge or Internet Explorer

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#658]
During a training, it appeared that ideascube does not allow users to log in if they use IE or edge, on Windows 10. As much as I'm proud of ideascube because it does an active advocacy for free and open source softwares, it's a problem for some of our projects, especially a colombian one, where our partner has already installed and configure 120 computers with only edge and IE. Sure it is their mistake, but we should help them to help themselves, and we should try to correct this ~~bug~~  active advocacy of ideascube.

Bug description : after filling the forms with the username and password, after we have clicked on "login", we are redirected to the home page, without being logged.

**Comment by bochecha** [comment]
As I mentioned yesterday on IRC, I can't reproduce it here.

I tested with Edge on an up to date Windows 10 machine.

**Comment by letompouce** [comment]
@barbayellow could you provide a list of installed extensions in both browsers?

**Comment by bochecha** [comment]
I suspect there's something fishy going on with the cookies.

That is, either the browsers are configured to refuse our cookies (we use one to store the authenticated user session), or as @letompouce an extension could be doing that.

I really can't find anything in Ideascube which could explain the problem, and I can't even reproduce it, either on Edge (Windows 10) or IE11 (Windows 7). 😕

**Comment by barbayellow** [comment]
Thx for trying. I think this is indeed a very localized issue. I tried again this morning wit 3 differents laptops and it worked. So this is sorcery. Sorry that you spent so much time on this but in the end this is  another victory for FLOSS because to be sure that librarians on the field won't have any problems, it has been decided to add Firefox on the 120 computers.
