### ISSUE TITLE
Inventory should be made with the barcode OR the serial

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#660]
Sometimes it is very useful to scan only the serial number rather than a barcode because some items don't have barcode but they have a serial number. That will avoid to stick a barcode sticker when there is already a serial. Ex : computers, tablets, ereaders.
Serial and barcode are both unique numbers so that makes sense.

**Comment by mgautierfr** [comment]
Does we need also to do it for Loan ?
User also has to enter the specimen codebar for loans and returns.

As a side question : Can we suppose barcode unique enough and assume there will be no serial number identical to a barcode ?
Said otherwise, can we have a specimen with barcode 1234567 and another one with serial 1234567 ?
How would we choose one from the other as a user only enter a number ?

**Comment by barbayellow** [comment]
@mgautierfr yes, it is especially useful for the loans. The barcode or the serial must be unique though.

Regarding the side question: it can happen in theory, but I think chances are as high as the fact that a meteorite could fall tomorrow on earth or my chances to win to the lottery. However, if that happens, the key should be the barcode.

**Comment by bochecha** [comment]
> Serial and barcode are both unique numbers so that makes sense.

We just found that the code currently doesn't enforce uniqueness of the `serial`: two specimens can have the same `serial`.

We could make it unique. However, that requires a data migration.

But some boxes might already have entered multiple specimens with the same `serial`, so the migration would need to handle that.

@barbayellow Should we make it unique? If so, what should we do during the migration when we encounter two specimens with the same serial?

**Comment by barbayellow** [comment]
IRL, there will never be 2 items with the same serial number. Serial numbers on the stickers are incremental. Here the process is supposed to guaranty that we will never have 2 identical serial number. I'm not sure it's worth a migration.
