### ISSUE TITLE
Apply last translation changes from transiflex

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#661]
In the library app in the spanish version, loggged as an admin : 
* "Importar notas" should be "Importar Resana"
* "Importar specimen" should be "Importar ejemplares"

The transiflex translation has already been updated. We just need to apply the changes in Ideascube. Does someone know how to do it ? ping @yohanboniface :)

**Comment by yohanboniface** [comment]
Pull translations from Transifex:

    make pull_translations
    make compile_translations

Push new strings to Transifex:

    make collect_translations
    make push_translations

**Comment by barbayellow** [comment]
thx!

**Comment by yohanboniface** [comment]
Note: `make compile_translations` may fail because the pulled translations are invalid (mainly because placeholders are respected, `%(foo)s` or `{foo}` and such), in this case you need to fix the translation on Transifex and pull again.

**Comment by bochecha** [comment]
```
/home/mathieu/.transifexrc not found.
Exception: No user credentials found for host https://www.transifex.com. Edit ~/.transifexrc and add the appropriate info in there.
```

I guess I need to dust off my old Transifex account.
