### ISSUE TITLE
What are those .old cards?

### ISSUE THREAD

**Issue by bochecha** [ideascube/ideascube#675]
I see quite a few setting files with card ids ending in `.old`, for example `ideascube/conf/idb_fra_cultura.py`:

```python
HOME_CARDS = HOME_CARDS + [
    {
        'id': 'cpassorcier.old',
    },
    {
        'id': 'wikisource.old',
    },
    {
        'id': 'ted.old',
    },
    {
        'id': 'ubuntudoc.old',
    },
]
```

What are these?

They seem to have been introduced in this commit:

```
commit 94003e8b3c75231d0226dd88fc94692b7b0a9445
Author: Yohan Boniface <yb@enix.org>
Date:   Thu Mar 10 19:37:13 2016 +0100

    Package manager aware static cards
```

The message is not very explicit, so I'm not sure what to understand.

There are even some of those `.old` cards in `ideascube/templates/ideascube/includes/cards/`.

Is that old stuff that became obsolete with the move to the package manager for content? Should we remove all of this?

**Comment by fheslouin** [comment]
These `.old` cards are used for zim files that are not managed by the catalog. 

These settings have to be keep until ansiblecube is going to be able to move zim files from old path to the new path managed by the catalog. It should happen soon !

**Comment by bochecha** [comment]
Thanks for the explanation. 👍 

Let's keep this open until that time then, so we don't forget to delete them in the glorious future. (who said "next August"?!)

**Comment by fheslouin** [comment]
AnsibleCube use `/etc/default/ideascube` and the `IDEASCUBE_ID=` variable
If a file in `ideascube/conf/` is found matching the device name, this file will be use and possibly some old cards `.old`

We have to take care of this and remove those `.old` lines and possibly `.py` files as zim migration are going
