### ISSUE TITLE
Media center : bulk media deletion

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#685]
We **need** a command (maybe it is unwise to add it in the UI) to delete massively medias in the media center.

We need to be able to delete: 
- all the medias 
- medias created between xxx and xxx (xxx is a date)

Additionally, it could be nice to have the ability to delete:
- medias type = video / audio / pdf / ...
- medias title = "insertyoursophisticatedregexhere"

**Comment by letompouce** [comment]
> We *need* a command (maybe it is unwise to add it in the UI) to delete
> massively medias in the media center.

For the time being, I can imagine some ugly hack based on `ideascube
dumpdata` / curl POST / `rm -f`. So please don't let me do that :D

**Comment by bochecha** [comment]
Once #684 is fixed, then a quick Django shell would be nicer:

```python
from ideascube.mediacenter.models import Document

for document in Document.objects.all():
    document.delete()
```

(the above is written entirely from memory, and is untested)

In fact, that's exactly what the command would end up doing.

I'm just mentioning it here to show you that the Django shell is not very complex, and is definitely much nicer than playing with `dumpdata` 😉
