### ISSUE TITLE
Battery in the top bar menu

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#692]
This is a huge feature, we need to have an indicator with the battery level on every pages, in the top right corner.

**Comment by bochecha** [comment]
What we discussed earlier today: it will eventually be all AJAX-y and asynchronous with real-time updates of the battery status, however we need to **also** have a static fallback without Javascript, where users must refresh the page to get the latest status.

The latter will require Cockpit, but we don't need to wait for it, we can implement the fallback path right away.
