### ISSUE TITLE
3gp multimedia container can not be read

### ISSUE THREAD

**Issue by fheslouin** [ideascube/ideascube#705]
3gp multimedia container format used by mobile device can not be read by the video player in the media-center. This format is widely used on mobile device, since we provide them, it will be great that the media-center will be able to read them.

Can we take care that other common medias are readable as well

**Comment by bochecha** [comment]
The mediacenter uses the HTML `<video>` tag.

That means the video player comes from the web browser, and the list of supported formats depend on the web browser.

There is not much we can do here.

Some possibilities include:

* on upload, automatically transcode the videos to a format we know is well supported by all major browsers, both mobile and desktop ones
* make our own full-featured web video player, going back to the good old days of Flash

I'd prefer the first one. However, transcoding videos on a Koombook might not be a great idea. 😉

It also raises UX questions: how to tell the user the video is being transcoded, which could potentially take a long time?
