### ISSUE TITLE
Enable link, don't remove new line 

### ISSUE THREAD

**Issue by fheslouin** [ideascube/ideascube#706]
The links are not enable in the media-center description, so users has to copy/paste them in the URL bar. 

New lines are also removed, so it make description as a big block of text which is not always really easy to read

**Comment by mgautierfr** [comment]
I've created the PR #711 to fixes this issue.
This does the job but it opens new question.

Do we allow html markup in the description ?
For now, this is not allowed and any html markup (`<div>`, `<a href="...">`, ...) are displayed as it has been written.

The solution I've implemented (using regex) works pretty well for simple (but most common) case but fails for more complex ones:
- `(https://foo.fr)` will detect the `)` as part of the address and will create a link to `https://foo.fr)`
- If a user want to enter the text `<a href="http://foo.fr">foo</a>` we should detect `http://foo.fr` but we will create a link to `http://foo.fr">foo</a>`

This cases are either easy to workaround (add a space before the `)`) or usecase that we can decide to ignore (thus the question about the html markup).

We could work on this and create more complex regex to handle those cases but I start wondering if this is the right solution :
- We could simply allow html markup in the description and let's user write the html tags needed to correctly display new line (`<br />`) or link (`<a href=...`). It would work but, 1. it's not easy for users to now which tag use, 2. we open ourselves to some potential security leaks.
- We could switch to a more simpler markup language (ie, markdown using the [django-markdown plugin](https://github.com/klen/django_markdown). It add another dependency to the project but simplify all this parsing (and adding more functionality like list creation, ...). And this dependency could also be used in the blog application that needs a lot of improvement/redesign.

**Comment by barbayellow** [comment]
Maybe we could go a little bit further and instead of using a regex, we could  add a rich text editor. this might also be useful for the blog since our current rich text editor does not allow us to add media in the blogposts #644 . One stone 2 birds.

**Comment by bochecha** [comment]
One thing to note though: in the blog, we want writers to be able to embed medias (pictures, videos, ...) in the content they write.

In the mediacenter's `description` field, we absolutely do not want that... since this is the description for a media. 😄 

So we need a rich text editor widget which allows us to chose what to allow. (e.g the buttons visible in the toolbar)

**Comment by barbayellow** [comment]
good point.
