### ISSUE TITLE
Update server packages

### ISSUE THREAD

**Issue by yohanboniface** [ideascube/ideascube#71]
A page to manage the apt update/upgrade of the server, so that people managing the server doesn't need to plug a display on the server to run the upgrades (or connect through SSH).

And there is a lib for that: http://apt.alioth.debian.org/python-apt-doc/index.html

**Comment by bochecha** [comment]
How would that fit with the whole "app/content store"?

Do we want this to be a separate page, to "update the system", and apps will be updated in the "store" page? Or should the system updates happen in the same page as the app updates?

If we want to separate them, how do we handle the fact that apps will be installed as `.deb` packages, and as such be quite tied to the system packages? (dependencies, etc...)
