### ISSUE TITLE
Tags in the media center are not displayed

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#713]
We have a pb in the media center : only the 20  (more or less) most used tags appear in the left column.
![image](https://cloud.githubusercontent.com/assets/4816690/22517762/87b61770-e8aa-11e6-83b2-893547063768.png)

We need to have a way to display all the tags. Pb : the users can enter any tag. So we might end with a page with & thousand tags. Which is something we don't want.

So we discussed on IRC about a short term solution : 
- the 20 (more or less) most used tags are still displayed by default. All th other tags are displayed in a select list, ordered by name.
- The form allowing a user to add a media (when logged as an admin) in the media center should also enable a kind of auto completion system for the tag files. Hence it will limit the number of tags created by the users.

**Comment by mgautierfr** [comment]
The c373bfd in PR #710 change the limit to 40. It is not a perfect solution but it allow us to mitigate this problem.
@bochecha also opened the issue #701 I'm working on.
Related to #698.

The completion system is still a valid improvement to make as we agree to have some js if we are logged as admin.
