### ISSUE TITLE
Wifi semi captive portal

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#714]
Not sure if this should be in ideascube or ansiblecube. But here it is : 
We should allow our users once they access to the wifi network created by ideascube to be redirected to ideasbox.lan or koombook.lan or bibliotecamovil.lan or whateverwewant.lan.

Steven and @fheslouin have discussed about this and found a solution relying on cookies + firewall + mac adresses registered. We don't want to MITM our users and we don't want to disable an Internet access too.

**Comment by letompouce** [comment]
Related issue https://github.com/ideascube/ansiblecube/issues/67
