### ISSUE TITLE
csv2pkg output does not give enough information

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#728]
When a csv is mis formatted (99,99% of the time), csv2 pkg only displays a message explaining that something is missing. But it does not say what : 

> Warnings
> - Metadata missing, ignoring the corresponding media (14)
> There is no (valid) media to create the package.
> No package will be created

In this case, we need then to use media_import (which uses the same sv file format) to have the details:
 > Errors
>- summary: * This field is required. (14)
>  . {'summary': '', 'preview': 'Suenan_los_androides.png', 'kind': 'pdf', 'title': '¿Sueñan los androides con alpacas eléctricas?', 'credits': 'Aristizábal Gáfaro, Jorge, 1964-', 'path': 'Suenan_los_androides.pdf', 'lang': 'Español', 'tags': 'Literatura'}
>  . {'summary': '', 'preview': 'Carmilla.png', 'kind': 'pdf', 'title': 'Carmilla', 'credits': 'Le Fanu, Joseph Sheridan, 1814-1873', 'path': 'Carmilla.pdf', 'lang': 'Español', 'tags': 'Literatura '}

It would be great to have this kind of details directly in csv2pkg. Actually it is needed.

**Comment by mgautierfr** [comment]
The missing metadata (and the corresponding line number) should be displayed with the `--verbosity 3` option.

I agree that is not evident to found. We could change that.
