### ISSUE TITLE
Switch to python3.4?

### ISSUE THREAD

**Issue by yohanboniface** [ideascube/ideascube#75]
Using dh_virtualenv to manage the Debian package allows us to use a different python than the system one. I'm in favour of switching to python 3 then, because this is present.

**Comment by benoitbryon** [comment]
Trying to figure out where Python version is set (i.e. what may be changed to resolve this issue), found:
* declaration in setup.py: https://github.com/ideas-box/ideasbox.lan/blob/0.3.3/setup.py#L36-L37
* Travis-CI configuration: https://github.com/ideas-box/ideasbox.lan/blob/0.3.3/.travis.yml#L2-L3
* installation instructions in docs/install.rst: https://github.com/ideas-box/ideasbox.lan/blob/0.3.3/docs/install.rst
* several references to `python` (should it be `python-3.4`?) in debian/. Example: https://github.com/ideas-box/ideasbox.lan/blob/0.3.3/debian/control#L5

What about listing these items as "tasks" in this issue's description?
Are there other items?

**Comment by benoitbryon** [comment]
Ideas to help issue resolution via incremental steps:
1. introduce Tox
2. use Tox to test compatibility with multiple Python versions
3. optionally drop support of Python 2.x

**Comment by yohanboniface** [comment]
> installation instructions in docs/install.rst: https://github.com/ideas-box/ideasbox.lan/blob/0.3.3/docs/install.rst

Side note: you may not have an up to date version project, I've switched to mkdocs recently ;)

> introduce Tox

Not sure about the advantages over just referencing all versions in Travis

> optionally drop support of Python 2.x

Not yet, I'm afraid :(

> What about listing these items as "tasks" in this issue's description?

Sure, can you do it or you are missing permissions?

> Are there other items?

Make the code work with python 3.4/5? ;)

One issue is that we are not sure to keep dh_virtualenv as package solution, because it needs downloading python packages at build time (via pip), and launchpad does not allow that. So we can't put Deb packages of the server on launchpad because of that :/
