### ISSUE TITLE
Things to do if we upgrade to Python 3.5 or change path

### ISSUE THREAD

**Issue by fheslouin** [ideascube/ideascube#754]
Path to the ideascube configuration file has been hardcoded in AnsibleCube. 
https://github.com/ideascube/ansiblecube/blob/oneUpdateFile/roles/ideascube/tasks/ideascube.yml#L108

We will have to change this path if we upgrade to python 3.5 or change path to ideascube folder

**Comment by bochecha** [comment]
> Path to the ideascube configuration file has been hardcoded in AnsibleCube.

You probably shouldn't have done that then.

This would have failed with the recent move to dh-virtualenv-1.0 for example.

**Comment by fheslouin** [comment]
Yes indeed it fails, that's why I posted this issue for next time :)

I'm opening an issue on ansiblecube side to avoid using an hardcoded path
