### ISSUE TITLE
What is the "Author text" for?

### ISSUE THREAD

**Issue by bochecha** [ideascube/ideascube#758]
I just did some UX test on the blog with someone who already has a blog (at Wordpress.com) but had never been exposed to Ideascube before.

I asked her to just create a new blog post, as if it were her blog.

The test happened on @mgautierfr's TinyMCE branch, which hides the `Author` field as requested in #344 

As a result, she was extremely confused by the `Author text` field. And to be honest, I couldn't really tell her what it was, without going to read the source code first.

If we're hiding the `Author` field, filling it up automatically with the staff user who writes the article, then we probably shouldn't show the `Author text` field either.

But then I'd go even further: do we need it at all? Should we completely remove the `Author text` field, if it serves no useful purpose?

**Comment by fheslouin** [comment]
I think author text was created for a multi-user use of the blog in mind.
I found it quite confusing as well as we can guess the user (the one 
logged in) and does not have any special use, even worse someone can 
cheat on some else writing something bad...

I think these field should be hidden as well.
