### ISSUE TITLE
Rework the blog status in the form

### ISSUE THREAD

**Issue by bochecha** [ideascube/ideascube#759]
_Note: This is related to a part of #344, but I'd like to elaborate on it and give its own issue, since some UX testing revealed a more fundamental problem_

---

When creating/editing a blog article, the user is presented with a `Status` field, where they must choose between one of these 3 values:

* draft
* published
* deleted

When **creating** an article, the `deleted` makes no sense: who in their right mind would create a deleted article?

But even in all other cases, the field still is confusing.

What would be much nicer would be to exclude the field from the form, and then replace the `Submit` button by three buttons:

* Save as draft
* Publish
* Delete (this one would obviously not be shown when creating an article, only when editing one)

User testing revealed that `published` and `deleted` were confusing as status values, because they are adjectives representing the end state. But the user model is more an action/verb: I want to delete this article, I want to save this draft.

**Comment by mgautierfr** [comment]
Reading your #344 issue, I was thinking about a checkbox "draft" or "published/public" depending of what default value we want to have. (And of course remove the `delete` field, at least at creation).

I don't know what is the better idea, but let's brainstorming :)
