### ISSUE TITLE
The image field is unclear

### ISSUE THREAD

**Issue by bochecha** [ideascube/ideascube#762]
I just did some UX test on the blog with someone who already has a blog (at Wordpress.com) but had never been exposed to Ideascube before.

I asked her to just create a new blog post, as if it were her blog.

She couldn't understand what the `Image` field was. Even after explaining it, she kept confusing it with a facility to add media inside the article.

This is an optional image to represent the article in the list, kind of like a "cover" for a book, or a "thumbnail" for a media.

We should probably try to find a better `verbose_name` (cover image? that doesn't seem great), or at least specify a useful `help_text`.

**Comment by fheslouin** [comment]
We should indeed find a better name for this field. Cover could be a 
good name for that purpose.

**Comment by bochecha** [comment]
Another option is to completely remove this field, and instead, if the author added images to the article content, then use the first as the cover/thumbnail in the list.
