### ISSUE TITLE
Using a big image breaks the list view

### ISSUE THREAD

**Issue by bochecha** [ideascube/ideascube#769]
A blog article can have an optional "image" to represent it in the list view.

We don't enforce a maximum size for this image.

Using a big one makes the list view look terrible.

We could enforce a maximum size:

* PRO: it would save disk space on the box
* PRO: it would make the list faster to load
* CON: it might be hard for some users to understand how to resize an image

Alternatively, we could resize the image upon uploading:

* PRO: it would save disk space on the box
* PRO: it would make the list faster to load
* PRO: users don't need to do it
* CON: we need to do more work on the box, which means installing some dependencies and maybe slightly increase the load (but that might be trivial)

Or, we could just specify a `max-height` style attribute to the images in the list:

* PRO: users don't need to bother with resizing
* PRO: it is a trivial solution to implement
* CON: we potentially store big images on the box, even though we display them small
* CON: we potentially make the page long to load, even though we display small images

**Comment by mgautierfr** [comment]
Working on the blog, I was a bit confuse with this image.
This image is only displayed on the list view. Never on the blog itself. A user could use two different images as "icon image" and "content image" (image in the blog). This is pretty confusing when you click on a blog entry in the list (with a icon and a summary) and arrive on a blog post with a different image and (potentially) different texts (the summary and text are two independent fields so a user can enter what he want).

More over, the "icon image" and "content image" don't use the same upload process.
The "content image" are mainly oembed media and are linking external resources (that could be in the mediacenter). The "icon image" are uploaded from the local user computer. Thus we can easily assume that the icon image and the content image will be almost never be the sames.

There is a lot more to do than just limiting the size of the icon image. Maybe :
 - Remove it.
 - Allow user to upload image as content image (tinyMCE has a way to let us handle the upload, but we have to implement the right callbacks)
 - Always display the icon image in the blog content (but we have to change our form layout to correctly let the user see what will happen)

**Comment by bochecha** [comment]
> There is a lot more to do than just limiting the size of the icon image. Maybe :

Right, those are for #762 

The present issue is specifically "if we keep the image, then we must make sure it's not too big in the list".
