### ISSUE TITLE
Simplify uplaod form for content

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#775]
Too many fields are mandatroy in the  meia uplaod form :  http://koombook.lan/fr/mediacenter/document/new/

We should allow a  user to enter all  the operations : 
type, and authorship are not relevant and authorshi

**Comment by bochecha** [comment]
You seem to have sent the bug report before finishing your sentence. 😄

**Comment by barbayellow** [comment]
yes :) Here is the full comment : 

> Too many fields are mandatory in the media upload form : http://koombook.lan/fr/mediacenter/document/new/

Only "title" and "Source File" should be mandatory. The "type" should be automatically discovered by  ideascube - and thus disappear from this form.

The less we ask to users, the easiest it is for them to add content.
