### ISSUE TITLE
User Form for DRC server 

### ISSUE THREAD

**Issue by Narjis89** [ideascube/ideascube#784]
we been facing the same issue with register new user Form , we asked to update the form by adding other field and they are:
1- DRC- Number : they have unique number for each beneficiary the have and they want to us it   instead of the IDB number on the membership card 
2- Name
3- Full name 
4- Gender
5- phone number
6- Date of birth 
7- Nationality
8- UNHCR number 
9- National ID number
10- Address 
11- Disability : want it yes or no choice  
12- type of Disability 
If can we manage update it locally on the server for the fields than we can have , and for the next release of the the ideas-cube we can think of way to make the form manageable by the IDB Admin like we did with manage home page .

**Comment by bochecha** [comment]
Ideascube moved to Framagit.

This issue has been migrated.

Please continue the conversation there:

https://framagit.org/ideascube/ideascube/issues/784
