### ISSUE TITLE
Limit string length for titles on package/mediacenter view

### ISSUE THREAD

**Issue by swbsf** [ideascube/ideascube#793]
Didn't see if this issue was created already or not. Sorry if so :)
Title are truncated or simply badly displayed if too long. Limiting number of characters seems a good idea. See screenshot.
Thank you!
![image](https://cloud.githubusercontent.com/assets/22593912/24865131/a12de50c-1e06-11e7-8d38-7d319b510730.png)

**Comment by mgautierfr** [comment]
There are two bugs here :
- A technical one : We should not display icons on top of the text.
- A design one : Is it a good idea to have too long titles ?

We can handle the first one.

The second one is more a opened discussion and would globally depends of the design we want to have. (And, for the technical side, if we agree to limit the length we can of course do it)

**Comment by swbsf** [comment]
@barbayellow do we agree? To agree or not to agree, that's the question :)
As for the top icons "VIDEO" in this example. Yes we need to keep them as we could have text document and videos in the same package. But you know this. Are we talking about the same icon? Not sure anymore...

**Comment by mgautierfr** [comment]
I'm not speaking of the "VIDÉO" tags (with green background).
I'm speaking of the preview imagei displayed above the title.
The preview should be displayed after the title, what ever is the title length.

**Comment by swbsf** [comment]
Got it... the preview below the title. That's indeed another good option. Titles can be quite long though, limiting displayed number of character could be a good idea still.
