### ISSUE TITLE
batch adding of specimens to create stock

### ISSUE THREAD

**Issue by yohanboniface** [ideascube/ideascube#92]

**Comment by barbayellow** [comment]
This one could be extremely useful in the coming months. The lack of this feature is one of the main reason why the stock app is not being used, at least in France. Since around 50% of each ideasbox content is identical from a project to another, a csv batch import file could be a solution.

**Comment by yohanboniface** [comment]
I think your are mixing two things here ;)
What you want is an import of stock *items* from a CSV file, while this issue is for adding more than one *specimen* at a time.
Let me try to be a bit more explicit :)
Stock are composed of **items** (like a television, a usb cable, a tablet, etc.). Those items are like metadatas. Any of those items has one or more **specimens**. A specimen is the physical representation of the item, including most of the time a serial number (and thus a barcode sticker, for example for the television or the tablets), or at least a counter (for cables for example).

In brief: your need needs another issue :)

**Comment by barbayellow** [comment]
Understood! I opened a new issue > #304
