### ISSUE TITLE
Create an UI to change the wifi password

### ISSUE THREAD

**Issue by yohanboniface** [ideascube/ideascube#98]
Replacing by regex on the hostapd.conf file?

**Comment by fheslouin** [comment]
Good idea, it is really needed. For instance, I would like to have the choice between open access hotspot and secured hotspot. I simple switch will do the job

**Comment by fheslouin** [comment]
In RDC we really need this feature because password will be given to student and will have to be changed time to time. @gawel started to develop this nice feature, I think we could finish easily the job

**Comment by yohanboniface** [comment]
cf #221

**Comment by fheslouin** [comment]
Reminder : The hostapd password must be > 8 chars
